// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: rag/admin/v1/ai_knowledge_doc.proto

/* eslint-disable */
import type { Empty } from "../../../google/protobuf/empty";

/** AI知识库文档处理状态枚举。 */
export enum AiKnowledgeDocStatus {
  /** AI_KNOWLEDGE_DOC_STATUS_UNSPECIFIED - 未指定文档处理状态。 */
  AI_KNOWLEDGE_DOC_STATUS_UNSPECIFIED = 0,
  /** AI_KNOWLEDGE_DOC_STATUS_READY - 处理完成。 */
  AI_KNOWLEDGE_DOC_STATUS_READY = 1,
  /** AI_KNOWLEDGE_DOC_STATUS_FAILED - 处理失败。 */
  AI_KNOWLEDGE_DOC_STATUS_FAILED = 2,
}

/** 分页查询知识库文档请求。 */
export interface PageAiKnowledgeDocRequest {
  /** 知识库ID */
  id: number;
  /** 当前页码 */
  page_num: number;
  /** 每页行数 */
  page_size: number;
}

/** 分页查询知识库文档响应。 */
export interface PageAiKnowledgeDocResponse {
  /** 文档列表 */
  docs: AiKnowledgeDoc[];
  /** 总数 */
  total: number;
}

/** AI知识库文档。 */
export interface AiKnowledgeDoc {
  /** 文档ID */
  id: number;
  /** 知识库ID */
  knowledge_base_id: number;
  /** 文档名称 */
  name: string;
  /** 切片数 */
  chunk_count: number;
  /** 处理状态：枚举【AiKnowledgeDocStatus】 */
  status: AiKnowledgeDocStatus;
  /** 失败原因 */
  error_message: string;
  /** 创建时间 */
  created_at: string;
}

/** 上传纯文本文档请求。 */
export interface UploadAiKnowledgeDocTextRequest {
  /** 知识库ID */
  id: number;
  /** 文档名称 */
  name: string;
  /** 文档文本内容 */
  content: string;
}

/** 上传文档文件请求。 */
export interface UploadAiKnowledgeDocFileRequest {
  /** 知识库ID */
  id: number;
  /** 原始文件名 */
  file_name: string;
  /** 文件内容（≤10MB） */
  content_base64: Uint8Array;
  /** 文档显示名 */
  doc_name: string;
}

/** 删除文档请求。 */
export interface DeleteAiKnowledgeDocRequest {
  /** 文档ID */
  doc_id: number;
}

/** 重新处理文档请求。 */
export interface ReprocessAiKnowledgeDocRequest {
  /** 文档ID */
  doc_id: number;
}

/** AI知识库文档管理服务。 */
export interface AiKnowledgeDocService {
  /** 分页查询知识库下的文档。 */
  PageAiKnowledgeDoc(request: PageAiKnowledgeDocRequest): Promise<PageAiKnowledgeDocResponse>;
  /** 上传纯文本文档（切片 → 向量化 → 落库）。 */
  UploadAiKnowledgeDocText(request: UploadAiKnowledgeDocTextRequest): Promise<Empty>;
  /** 上传文档文件（txt/md/docx/pdf：抽取文本后走同一入库链）。 */
  UploadAiKnowledgeDocFile(request: UploadAiKnowledgeDocFileRequest): Promise<Empty>;
  /** 删除文档（级联删除切片）。 */
  DeleteAiKnowledgeDoc(request: DeleteAiKnowledgeDocRequest): Promise<Empty>;
  /** 重新处理失败的文档（按保存的原文重切片、重向量化）。 */
  ReprocessAiKnowledgeDoc(request: ReprocessAiKnowledgeDocRequest): Promise<Empty>;
}
