// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: rag/admin/v1/ai_knowledge_chunk.proto

/* eslint-disable */

/** 检索测试请求。 */
export interface SearchAiKnowledgeRequest {
  /** 知识库ID */
  id: number;
  /** 检索关键词 */
  query: string;
  /** 返回切片数量 */
  top_k: number;
}

/** 检索测试响应。 */
export interface SearchAiKnowledgeResponse {
  /** 语义最相近的切片 */
  hits: AiKnowledgeChunkHit[];
}

/** 检索命中的切片。 */
export interface AiKnowledgeChunkHit {
  /** 切片ID */
  chunk_id: number;
  /** 文档ID */
  doc_id: number;
  /** 文档名称 */
  doc_name: string;
  /** 切片文本 */
  content: string;
  /** 余弦相似度 */
  score: number;
}

/** AI知识库切片检索服务。 */
export interface AiKnowledgeChunkService {
  /** 检索测试：返回与query语义最相近的切片。 */
  SearchAiKnowledge(request: SearchAiKnowledgeRequest): Promise<SearchAiKnowledgeResponse>;
}
