// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               unknown
// source: rag/admin/v1/ai_knowledge.proto

/* eslint-disable */
import type { Empty } from "../../../google/protobuf/empty";

/** AI知识库分页查询条件。 */
export interface PageAiKnowledgeRequest {
  /** 知识库名称 */
  name: string;
  /** 当前页码 */
  page_num: number;
  /** 每页行数 */
  page_size: number;
}

/** AI知识库分页响应。 */
export interface PageAiKnowledgeResponse {
  /** 知识库列表 */
  knowledges: AiKnowledge[];
  /** 总数 */
  total: number;
}

/** 查询AI知识库请求。 */
export interface GetAiKnowledgeRequest {
  /** 知识库ID */
  id: number;
}

/** AI知识库维护表单。 */
export interface AiKnowledgeForm {
  /** 知识库ID */
  id: number;
  /** 知识库名称 */
  name: string;
  /** 描述 */
  description: string;
  /** 向量维度；0表示按所选模型配置或系统默认 */
  embedding_dimensions: number;
  /** 向量化使用的embedding模型ID */
  model_id: number;
}

/** 创建AI知识库请求。 */
export interface CreateAiKnowledgeRequest {
  /** AI知识库表单 */
  ai_knowledge: AiKnowledgeForm | undefined;
}

/** 更新AI知识库请求。 */
export interface UpdateAiKnowledgeRequest {
  /** AI知识库表单 */
  ai_knowledge: AiKnowledgeForm | undefined;
}

/** 删除AI知识库请求。 */
export interface DeleteAiKnowledgeRequest {
  /** 知识库ID */
  id: number;
}

/** AI知识库分页记录。 */
export interface AiKnowledge {
  /** 知识库ID */
  id: number;
  /** 知识库名称 */
  name: string;
  /** 描述 */
  description: string;
  /** embedding模型所属供应商名称 */
  provider_name: string;
  /** embedding向量维度 */
  embedding_dimensions: number;
  /** 向量化使用的embedding模型ID */
  model_id: number;
  /** embedding模型名称 */
  model_name: string;
  /** 文档数量 */
  doc_count: number;
  /** 创建时间 */
  created_at: string;
  /** 更新时间 */
  updated_at: string;
}

/** 查询embedding模型选项请求。 */
export interface ListAiKnowledgeModelsRequest {
}

/** 查询embedding模型选项响应。 */
export interface ListAiKnowledgeModelsResponse {
  /** 已启用的embedding模型列表 */
  models: AiKnowledgeModel[];
}

/** 知识库可用的embedding模型选项。 */
export interface AiKnowledgeModel {
  /** 模型ID */
  id: number;
  /** 模型所属供应商名称 */
  provider_name: string;
  /** 模型名称 */
  model_name: string;
  /** 显示名称 */
  display_name: string;
  /** 模型声明的输出向量维度；0表示未声明 */
  dimensions: number;
  /** 可选向量维度列表 */
  dimension_options: number[];
}

/** AI知识库管理服务。 */
export interface AiKnowledgeService {
  /** 分页查询AI知识库。 */
  PageAiKnowledge(request: PageAiKnowledgeRequest): Promise<PageAiKnowledgeResponse>;
  /**
   * 查询已启用的embedding模型选项（知识库向量化模型下拉）。
   * 字面路径必须先于 /{id} 声明：gorilla mux 按注册顺序匹配，否则会被 {id} 路由抢占。
   */
  ListAiKnowledgeModels(request: ListAiKnowledgeModelsRequest): Promise<ListAiKnowledgeModelsResponse>;
  /** 查询AI知识库表单。 */
  GetAiKnowledge(request: GetAiKnowledgeRequest): Promise<AiKnowledgeForm>;
  /** 创建AI知识库。 */
  CreateAiKnowledge(request: CreateAiKnowledgeRequest): Promise<Empty>;
  /** 更新AI知识库。 */
  UpdateAiKnowledge(request: UpdateAiKnowledgeRequest): Promise<Empty>;
  /** 删除AI知识库（级联删除文档与切片）。 */
  DeleteAiKnowledge(request: DeleteAiKnowledgeRequest): Promise<Empty>;
}
