// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: admin/base_migration.proto

package admin

import (
	"context"
	"fmt"

	systemadminv1 "github.com/liujitcn/kratos-admin/backend/api/gen/go/system/admin/v1"
	"github.com/liujitcn/kratos-admin/backend/core/pkg/errorsx"
	biz "github.com/liujitcn/kratos-admin/backend/internal/biz/admin"

	"github.com/go-kratos/kratos/v3/log"
	"google.golang.org/grpc"
)

const _ = grpc.SupportPackageIsVersion7

// BaseMigrationService 数据库迁移服务。
type BaseMigrationService struct {
	systemadminv1.UnimplementedBaseMigrationServiceServer
	baseMigrationCase *biz.BaseMigrationCase
}

// NewBaseMigrationService 创建数据库迁移服务。
func NewBaseMigrationService(baseMigrationCase *biz.BaseMigrationCase) *BaseMigrationService {
	return &BaseMigrationService{baseMigrationCase: baseMigrationCase}
}

// PageBaseMigration 分页查询数据库升级历史。
func (s *BaseMigrationService) PageBaseMigration(
	ctx context.Context,
	req *systemadminv1.PageBaseMigrationRequest,
) (*systemadminv1.PageBaseMigrationResponse, error) {
	res, err := s.baseMigrationCase.PageBaseMigration(ctx, req)
	if err != nil {
		log.Error(fmt.Sprintf("PageBaseMigration %v", err))
		return nil, errorsx.WrapInternal(err, "查询数据库升级历史失败")
	}
	return res, nil
}

// GetBaseMigration 查询数据库迁移记录详情。
func (s *BaseMigrationService) GetBaseMigration(
	ctx context.Context,
	req *systemadminv1.GetBaseMigrationRequest,
) (*systemadminv1.BaseMigration, error) {
	res, err := s.baseMigrationCase.GetBaseMigration(ctx, req.GetId())
	if err != nil {
		log.Error(fmt.Sprintf("GetBaseMigration %v", err))
		return nil, errorsx.WrapInternal(err, "查询数据库迁移记录详情失败")
	}
	return res, nil
}
