// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               unknown
// source: base/v1/ai_knowledge.proto

/* eslint-disable */

/** AI知识库选项查询请求。 */
export interface ListAiKnowledgeOptionsRequest {
}

/** AI知识库选项查询响应。 */
export interface ListAiKnowledgeOptionsResponse {
  /** 知识库选项列表 */
  options: AiKnowledgeOption[];
}

/** AI知识库选项。 */
export interface AiKnowledgeOption {
  /** 知识库ID */
  id: number;
  /** 知识库名称 */
  name: string;
  /** 已就绪文档数，不含处理失败 */
  doc_count: number;
}

/** AI 知识库选项查询服务。 */
export interface AiKnowledgeService {
  /** 查询可用的AI知识库选项。 */
  ListAiKnowledgeOptions(request: ListAiKnowledgeOptionsRequest): Promise<ListAiKnowledgeOptionsResponse>;
}
