// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               unknown
// source: base/v1/login.proto

/* eslint-disable */
import type { SecretCrypto } from "../../common/v1/types";
import type { Empty } from "../../google/protobuf/empty";

/**
 * LoginStatus 表示登录请求当前所处的认证阶段。
 * 只有 AUTHENTICATED 或 PASSWORD_CHANGE_REQUIRED 才会携带正式访问令牌，MFA 状态必须继续完成挑战。
 */
export enum LoginStatus {
  /** LOGIN_STATUS_UNSPECIFIED - 未指定登录状态。 */
  LOGIN_STATUS_UNSPECIFIED = 0,
  /** LOGIN_STATUS_AUTHENTICATED - 已完成认证并签发令牌。 */
  LOGIN_STATUS_AUTHENTICATED = 1,
  /** LOGIN_STATUS_MFA_REQUIRED - 需要继续校验多因素认证。 */
  LOGIN_STATUS_MFA_REQUIRED = 2,
  /** LOGIN_STATUS_MFA_ENROLLMENT_REQUIRED - 必须先完成多因素认证绑定。 */
  LOGIN_STATUS_MFA_ENROLLMENT_REQUIRED = 3,
  /** LOGIN_STATUS_PASSWORD_CHANGE_REQUIRED - 下次操作前必须修改临时密码。 */
  LOGIN_STATUS_PASSWORD_CHANGE_REQUIRED = 4,
}

/** 验证码获取条件 */
export interface CaptchaRequest {
  /** 验证码类型，random 表示随机选择当前支持的验证码类型 */
  type: string;
}

/** 登出请求条件 */
export interface LogoutRequest {
}

/** 验证码响应 */
export interface CaptchaResponse {
  /** 验证码ID。 */
  captcha_id: string;
  /** 验证码base64 */
  captcha_base64: string;
  /** 本次验证码实际类型 */
  type: string;
}

/** 验证码预校验请求 */
export interface VerifyCaptchaRequest {
  /** 验证码ID */
  captcha_id: string;
  /** 验证码答案 */
  captcha_code: string;
}

/** 验证码预校验响应 */
export interface VerifyCaptchaResponse {
  /** 验证码通过令牌 */
  captcha_token: string;
  /** 有效时间，单位秒 */
  expires_in: number;
}

/** 刷新令牌请求参数 */
export interface RefreshTokenRequest {
  /** 更新令牌；未填写时由服务端从HttpOnly Cookie读取。 */
  refresh_token?: string | undefined;
}

/** 刷新令牌响应 */
export interface RefreshTokenResponse {
  /** 访问令牌，必选项。 */
  access_token: string;
  /** 更新令牌；管理端 Cookie-only 请求不在响应体返回，应用端请求可返回。 */
  refresh_token: string;
  /** 令牌类型，该值大小写不敏感，必选项，可以是bearer类型或mac类型。 */
  token_type: string;
  /** 令牌有效时间，单位为秒。如果访问令牌过期，服务器应回复授予访问令牌的持续时间。如果省略该参数，必须其他方式设置过期时间。 */
  expires_in: number;
}

/** 登录请求参数 */
export interface LoginRequest {
  /** 租户编码 */
  tenant_code: string;
  /** 用户名，必选项。 */
  user_name: string;
  /** 用户的密码，必选项。 */
  password:
    | SecretCrypto
    | undefined;
  /** 验证码 */
  captcha_code: string;
  /** 验证码Id */
  captcha_id: string;
}

/** 登录响应 */
export interface LoginResponse {
  /** 访问令牌，必选项。 */
  access_token: string;
  /** 更新令牌；管理端 Cookie-only 请求不在响应体返回，应用端请求可返回。 */
  refresh_token: string;
  /** 令牌类型，该值大小写不敏感，必选项，可以是bearer类型或mac类型。 */
  token_type: string;
  /** 令牌有效时间，单位为秒。如果访问令牌过期，服务器应回复授予访问令牌的持续时间。如果省略该参数，必须其他方式设置过期时间。 */
  expires_in: number;
  /** 登录认证状态 */
  status: LoginStatus;
  /** 多因素认证挑战ID */
  mfa_challenge_id: string;
  /** 多因素认证绑定临时票据 */
  mfa_setup_ticket: string;
  /** 多因素认证挑战或绑定票据有效时间，单位秒 */
  mfa_expires_in: number;
  /** 多因素认证方式：totp、webauthn */
  mfa_method: string;
  /** WebAuthn认证选项JSON */
  mfa_webauthn_options_json: string;
  /** 当前登录策略允许的MFA设备免验证天数 */
  mfa_remember_days: number;
}

/** Base登录公共服务 */
export interface LoginService {
  /** 验证码 */
  Captcha(request: CaptchaRequest): Promise<CaptchaResponse>;
  /** 验证码预校验 */
  VerifyCaptcha(request: VerifyCaptchaRequest): Promise<VerifyCaptchaResponse>;
  /** 登出 */
  Logout(request: LogoutRequest): Promise<Empty>;
  /** 刷新认证令牌 */
  RefreshToken(request: RefreshTokenRequest): Promise<RefreshTokenResponse>;
  /** 登录 */
  Login(request: LoginRequest): Promise<LoginResponse>;
}
