// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package kratosadmin

import (
	"github.com/go-kratos/kratos/v3"
	"github.com/liujitcn/kratos-admin/backend/core/pkg/sse"
	"github.com/liujitcn/kratos-admin/backend/core/pkg/task"
	"github.com/liujitcn/kratos-admin/backend/internal/agent/model"
	"github.com/liujitcn/kratos-admin/backend/internal/biz"
	biz3 "github.com/liujitcn/kratos-admin/backend/internal/biz/admin"
	"github.com/liujitcn/kratos-admin/backend/internal/biz/admin/codegen"
	biz4 "github.com/liujitcn/kratos-admin/backend/internal/biz/app"
	biz2 "github.com/liujitcn/kratos-admin/backend/internal/biz/base"
	"github.com/liujitcn/kratos-admin/backend/internal/biz/base/ai"
	"github.com/liujitcn/kratos-admin/backend/internal/biz/event"
	"github.com/liujitcn/kratos-admin/backend/internal/biz/job"
	"github.com/liujitcn/kratos-admin/backend/internal/config"
	"github.com/liujitcn/kratos-admin/backend/internal/data/gen/data"
	"github.com/liujitcn/kratos-admin/backend/internal/server"
	admin2 "github.com/liujitcn/kratos-admin/backend/internal/server/admin"
	app2 "github.com/liujitcn/kratos-admin/backend/internal/server/app"
	base2 "github.com/liujitcn/kratos-admin/backend/internal/server/base"
	"github.com/liujitcn/kratos-admin/backend/internal/server/middleware"
	"github.com/liujitcn/kratos-admin/backend/internal/service/admin"
	"github.com/liujitcn/kratos-admin/backend/internal/service/app"
	"github.com/liujitcn/kratos-admin/backend/internal/service/base"
	"github.com/liujitcn/kratos-admin/backend/projectdoc"
	"github.com/liujitcn/kratos-kit/bootstrap"
	"github.com/liujitcn/kratos-kit/cache"
	"github.com/liujitcn/kratos-kit/database/gorm"
	"github.com/liujitcn/kratos-kit/database/gorm/migration"
	"github.com/liujitcn/kratos-kit/oauth"
	"github.com/liujitcn/kratos-kit/oss"
	"github.com/liujitcn/kratos-kit/pprof"
	"github.com/liujitcn/kratos-kit/queue"
)

// Injectors from wire.go:

// initModule 生成 Backend 模块内部依赖装配代码。
func initModule(context *bootstrap.Context, additionalModules AdditionalModules, configuredDocuments projectdoc.ConfiguredDocuments, arg []gorm.ClientOption, arg2 []migration.Contributor) (*Runtime, func(), error) {
	configv1Data, err := config.ParseData(context)
	if err != nil {
		return nil, nil, err
	}
	data_Redis := config.ParseRedis(configv1Data)
	cacheCache, cleanup, err := cache.NewCache(data_Redis)
	if err != nil {
		return nil, nil, err
	}
	data_Queue := config.ParseQueue(configv1Data)
	queueQueue, cleanup2, err := queue.NewQueue(data_Redis, data_Queue)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	registry, err := migration.NewRegistry(arg2)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	runner, err := migration.NewRunner(registry)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	client, cleanup3, err := config.NewDatabaseClient(configv1Data, arg, runner)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	ready := migration.NewReady(client)
	configv1Pprof, err := config.ParsePprof(context)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	pprofPprof, err := pprof.NewPprof(configv1Pprof)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	baseCase, cleanup4, err := biz.NewBaseCase(context, cacheCache, queueQueue, client, ready, pprofPprof)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	dataData := data.NewData(client)
	transaction := data.NewTransaction(dataData)
	aiSessionRepository := data.NewAiSessionRepository(dataData)
	aiMessageRepository := data.NewAiMessageRepository(dataData)
	aiSessionCase := biz2.NewAiSessionCase(baseCase, transaction, aiSessionRepository, aiMessageRepository)
	baseAPIRepository := data.NewBaseAPIRepository(dataData)
	baseUserRepository := data.NewBaseUserRepository(dataData)
	baseUserCase := biz2.NewBaseUserCase(baseUserRepository)
	ai_Model := config.ParseAIModel(context)
	responsesClient := model.NewResponsesClient(ai_Model)
	runtime := ai.NewRuntime(responsesClient)
	aiMessageCase := biz2.NewAiMessageCase(baseCase, transaction, aiMessageRepository, aiSessionCase, baseAPIRepository, baseUserCase, runtime)
	aiSessionService := base.NewAiSessionService(aiSessionCase, aiMessageCase)
	aiToolCase := biz2.NewAiToolCase(runtime)
	aiToolService := base.NewAiToolService(aiToolCase)
	aiMessageService := base.NewAiMessageService(aiMessageCase)
	baseConfigRepository := data.NewBaseConfigRepository(dataData)
	configCase := biz2.NewConfigCase(baseConfigRepository)
	configService := base.NewConfigService(configCase)
	configv1Oss, err := config.ParseOSS(context)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	ossOSS := oss.NewOSS(configv1Oss)
	fileCase := biz2.NewFileCase(ossOSS)
	fileService := base.NewFileService(fileCase)
	authentication_Jwt := config.ParseAuthnJWT(context)
	authenticator := middleware.NewAuthenticator(authentication_Jwt)
	userToken := middleware.NewUserToken(authentication_Jwt, cacheCache, authenticator)
	baseDeptRepository := data.NewBaseDeptRepository(dataData)
	baseDeptCase := biz2.NewBaseDeptCase(baseDeptRepository)
	baseRoleRepository := data.NewBaseRoleRepository(dataData)
	baseTenantRepository := data.NewBaseTenantRepository(dataData)
	baseRoleCase := biz2.NewBaseRoleCase(baseRoleRepository, baseTenantRepository)
	baseDictRepository := data.NewBaseDictRepository(dataData)
	baseDictItemRepository := data.NewBaseDictItemRepository(dataData)
	loginCase := biz2.NewLoginCase(baseCase, userToken, baseDeptCase, baseRoleCase, baseUserCase, baseTenantRepository, baseDictRepository, baseDictItemRepository)
	loginService := base.NewLoginService(loginCase)
	oAuth := config.ParseOAuth(context)
	manager, err := oauth.NewManager(oAuth)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	baseThirdAccountRepository := data.NewBaseThirdAccountRepository(dataData)
	baseThirdAccountCase := biz2.NewBaseThirdAccountCase(baseThirdAccountRepository)
	userEvents := event.NewUserEvents()
	oauthCase := biz2.NewOauthCase(baseCase, transaction, manager, baseThirdAccountCase, baseUserCase, baseRoleCase, baseDeptCase, loginCase, configCase, userEvents)
	oauthService := base.NewOauthService(oauthCase)
	mcpServer, err := server.NewMCPHandler(context)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	mcpCase, err := biz2.NewMcpCase(context, baseAPIRepository, mcpServer)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	mcpService := base.NewMcpService(mcpCase)
	sseServer, err := base2.NewSSEHandler(context)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	sseRegistry := sse.NewRegistry()
	publisher := sse.NewPublisher(sseServer)
	codegenManager := codegen.NewManager()
	sseCase, err := biz2.NewSseCase(context, authenticator, userToken, sseServer, sseRegistry, publisher, codegenManager)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	sseService := base.NewSseService(sseCase)
	services := base2.Services{
		AiSession: aiSessionService,
		AiTool:    aiToolService,
		AiMessage: aiMessageService,
		Config:    configService,
		File:      fileService,
		Login:     loginService,
		Oauth:     oauthService,
		Mcp:       mcpService,
		Sse:       sseService,
	}
	basePostRepository := data.NewBasePostRepository(dataData)
	casbinRuleRepository := data.NewCasbinRuleRepository(dataData)
	baseMenuRepository := data.NewBaseMenuRepository(dataData)
	openapiRegistry, err := server.NewOpenAPIRegistry()
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	baseAPICase := biz3.NewBaseAPICase(baseCase, baseAPIRepository, authentication_Jwt, openapiRegistry)
	engine, err := middleware.NewAuthzEngine()
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	casbinRuleCase, err := biz3.NewCasbinRuleCase(casbinRuleRepository, transaction, baseMenuRepository, baseRoleRepository, baseTenantRepository, baseAPICase, engine)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	bizBaseRoleCase := biz3.NewBaseRoleCase(baseCase, transaction, baseRoleRepository, baseTenantRepository, casbinRuleCase)
	bizBaseDeptCase := biz3.NewBaseDeptCase(baseCase, baseDeptRepository)
	baseMenuCase := biz3.NewBaseMenuCase(baseCase, transaction, baseMenuRepository, baseRoleRepository, casbinRuleCase)
	bizBaseUserCase := biz3.NewBaseUserCase(baseCase, transaction, baseUserRepository, baseDeptRepository, basePostRepository, bizBaseRoleCase, bizBaseDeptCase, baseMenuCase, baseRoleCase, userEvents)
	baseTenantCase := biz3.NewBaseTenantCase(baseCase, transaction, baseTenantRepository, baseDeptRepository, baseRoleRepository, baseUserRepository, casbinRuleRepository, casbinRuleCase, userEvents)
	authCase := biz3.NewAuthCase(baseCase, bizBaseUserCase, bizBaseRoleCase, bizBaseDeptCase, baseTenantCase, baseMenuCase, fileCase)
	authService := admin.NewAuthService(authCase)
	baseApiService := admin.NewBaseApiService(baseAPICase)
	baseAreaRepository := data.NewBaseAreaRepository(dataData)
	baseAreaCase := biz3.NewBaseAreaCase(baseCase, baseAreaRepository)
	baseAreaService := admin.NewBaseAreaService(baseAreaCase)
	baseConfigCase := biz3.NewBaseConfigCase(baseCase, baseConfigRepository)
	baseConfigService := admin.NewBaseConfigService(baseConfigCase)
	baseDeptService := admin.NewBaseDeptService(bizBaseDeptCase)
	baseDictItemCase := biz3.NewBaseDictItemCase(baseCase, baseDictRepository, baseDictItemRepository)
	baseDictCase := biz3.NewBaseDictCase(baseCase, baseDictRepository, baseDictItemCase)
	baseDictService := admin.NewBaseDictService(baseDictCase, baseDictItemCase)
	baseJobRepository := data.NewBaseJobRepository(dataData)
	baseJobLogRepository := data.NewBaseJobLogRepository(dataData)
	baseJobLogCase := biz3.NewBaseJobLogCase(baseCase, baseJobLogRepository)
	taskRegistry := task.NewRegistry()
	cronServer := job.NewCronServer(baseJobRepository, taskRegistry)
	baseJobCase := biz3.NewBaseJobCase(baseCase, baseJobRepository, baseJobLogCase, cronServer)
	baseJobService := admin.NewBaseJobService(baseJobCase, baseJobLogCase)
	baseLogRepository := data.NewBaseLogRepository(dataData)
	baseLogCase := biz3.NewBaseLogCase(baseCase, baseLogRepository)
	baseLogService := admin.NewBaseLogService(baseLogCase)
	baseMenuService := admin.NewBaseMenuService(baseMenuCase)
	basePostCase := biz3.NewBasePostCase(baseCase, transaction, basePostRepository, baseUserRepository)
	basePostService := admin.NewBasePostService(basePostCase)
	baseRoleService := admin.NewBaseRoleService(bizBaseRoleCase)
	baseTenantService := admin.NewBaseTenantService(baseTenantCase)
	baseThirdAccountService := admin.NewBaseThirdAccountService(baseThirdAccountCase)
	baseUserService := admin.NewBaseUserService(bizBaseUserCase)
	codeGenTableRepository := data.NewCodeGenTableRepository(dataData)
	codeGenColumnRepository := data.NewCodeGenColumnRepository(dataData)
	codeGenColumnCase := biz3.NewCodeGenColumnCase(codeGenColumnRepository, client, transaction, baseDictRepository, codeGenTableRepository)
	codeGenProtoRepository := data.NewCodeGenProtoRepository(dataData)
	codeGenProtoCase := biz3.NewCodeGenProtoCase(codeGenProtoRepository, transaction, baseAPIRepository, codeGenTableRepository, codeGenColumnCase)
	codeGenTableCase := biz3.NewCodeGenTableCase(codeGenTableRepository, client, transaction, baseDictRepository, baseDictItemRepository, baseMenuCase, codeGenColumnCase, codeGenProtoCase)
	baseMigrationRepository := data.NewBaseMigrationRepository(dataData)
	baseMigrationCase := biz3.NewBaseMigrationCase(baseCase, baseMigrationRepository)
	codeGenCase := biz3.NewCodeGenCase(baseCase, transaction, baseAPICase, codeGenTableCase, codeGenColumnCase, codeGenProtoCase, baseMenuCase, baseMigrationCase, client, codegenManager)
	codeGenService := admin.NewCodeGenService(codeGenCase)
	codeGenColumnService := admin.NewCodeGenColumnService(codeGenColumnCase)
	codeGenProtoService := admin.NewCodeGenProtoService(codeGenProtoCase)
	codeGenTableService := admin.NewCodeGenTableService(codeGenTableCase)
	baseMigrationService := admin.NewBaseMigrationService(baseMigrationCase)
	additionalDocuments := newAdditionalProjectDocuments(additionalModules, configuredDocuments)
	catalog, err := newProjectDocumentCatalog(additionalDocuments)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	projectDocumentCase := biz3.NewProjectDocumentCase(catalog)
	projectDocumentService := admin.NewProjectDocumentService(projectDocumentCase)
	adminServices := admin2.Services{
		Auth:             authService,
		BaseAPI:          baseApiService,
		BaseArea:         baseAreaService,
		BaseConfig:       baseConfigService,
		BaseDept:         baseDeptService,
		BaseDict:         baseDictService,
		BaseJob:          baseJobService,
		BaseLog:          baseLogService,
		BaseMenu:         baseMenuService,
		BasePost:         basePostService,
		BaseRole:         baseRoleService,
		BaseTenant:       baseTenantService,
		BaseThirdAccount: baseThirdAccountService,
		BaseUser:         baseUserService,
		CodeGen:          codeGenService,
		CodeGenColumn:    codeGenColumnService,
		CodeGenProto:     codeGenProtoService,
		CodeGenTable:     codeGenTableService,
		BaseMigration:    baseMigrationService,
		ProjectDocument:  projectDocumentService,
	}
	baseUserCase2 := biz4.NewBaseUserCase(baseCase, baseUserRepository)
	bizAuthCase := biz4.NewAuthCase(baseCase, baseUserCase2, manager, userEvents)
	appAuthService := app.NewAuthService(bizAuthCase)
	bizBaseAreaCase := biz4.NewBaseAreaCase(baseCase, baseAreaRepository)
	appBaseAreaService := app.NewBaseAreaService(bizBaseAreaCase)
	bizBaseDictItemCase := biz4.NewBaseDictItemCase(baseCase, baseDictRepository, baseDictItemRepository)
	bizBaseDictCase := biz4.NewBaseDictCase(baseCase, baseDictRepository, bizBaseDictItemCase)
	appBaseDictService := app.NewBaseDictService(bizBaseDictCase)
	bizBaseMenuCase := biz4.NewBaseMenuCase(baseCase, baseMenuRepository)
	appBaseMenuService := app.NewBaseMenuService(bizBaseMenuCase)
	appServices := app2.Services{
		Auth:     appAuthService,
		BaseArea: appBaseAreaService,
		BaseDict: appBaseDictService,
		BaseMenu: appBaseMenuService,
	}
	modules := newModules(services, adminServices, appServices, additionalModules)
	httpMiddlewares := server.NewHTTPMiddleware(context, authenticator, baseUserRepository, engine, userToken, authentication_Jwt)
	grpcMiddlewares := server.NewGRPCMiddleware(context, authenticator, baseUserRepository, engine, userToken, authentication_Jwt)
	mcpToolsReady := server.NewMCPToolsReady(mcpServer, modules)
	agentToolsReady, err := server.NewAgentToolsReady(runtime, modules)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	openAPIReady, err := server.NewOpenAPIReady(context, baseAPICase, baseTenantCase, casbinRuleCase, openapiRegistry, modules)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	kratosadminRuntime, err := newRuntime(modules, httpMiddlewares, grpcMiddlewares, cronServer, openapiRegistry, baseConfigCase, projectDocumentCase, runtime, userEvents, mcpToolsReady, agentToolsReady, openAPIReady)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return kratosadminRuntime, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// initApp 生成 Backend 独立应用内部依赖装配代码。
func initApp(context *bootstrap.Context, additionalModules AdditionalModules, configuredDocuments projectdoc.ConfiguredDocuments, arg []gorm.ClientOption, arg2 []migration.Contributor) (*kratos.App, func(), error) {
	configv1Data, err := config.ParseData(context)
	if err != nil {
		return nil, nil, err
	}
	data_Redis := config.ParseRedis(configv1Data)
	cacheCache, cleanup, err := cache.NewCache(data_Redis)
	if err != nil {
		return nil, nil, err
	}
	data_Queue := config.ParseQueue(configv1Data)
	queueQueue, cleanup2, err := queue.NewQueue(data_Redis, data_Queue)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	registry, err := migration.NewRegistry(arg2)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	runner, err := migration.NewRunner(registry)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	client, cleanup3, err := config.NewDatabaseClient(configv1Data, arg, runner)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	ready := migration.NewReady(client)
	configv1Pprof, err := config.ParsePprof(context)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	pprofPprof, err := pprof.NewPprof(configv1Pprof)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	baseCase, cleanup4, err := biz.NewBaseCase(context, cacheCache, queueQueue, client, ready, pprofPprof)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	dataData := data.NewData(client)
	transaction := data.NewTransaction(dataData)
	aiSessionRepository := data.NewAiSessionRepository(dataData)
	aiMessageRepository := data.NewAiMessageRepository(dataData)
	aiSessionCase := biz2.NewAiSessionCase(baseCase, transaction, aiSessionRepository, aiMessageRepository)
	baseAPIRepository := data.NewBaseAPIRepository(dataData)
	baseUserRepository := data.NewBaseUserRepository(dataData)
	baseUserCase := biz2.NewBaseUserCase(baseUserRepository)
	ai_Model := config.ParseAIModel(context)
	responsesClient := model.NewResponsesClient(ai_Model)
	runtime := ai.NewRuntime(responsesClient)
	aiMessageCase := biz2.NewAiMessageCase(baseCase, transaction, aiMessageRepository, aiSessionCase, baseAPIRepository, baseUserCase, runtime)
	aiSessionService := base.NewAiSessionService(aiSessionCase, aiMessageCase)
	aiToolCase := biz2.NewAiToolCase(runtime)
	aiToolService := base.NewAiToolService(aiToolCase)
	aiMessageService := base.NewAiMessageService(aiMessageCase)
	baseConfigRepository := data.NewBaseConfigRepository(dataData)
	configCase := biz2.NewConfigCase(baseConfigRepository)
	configService := base.NewConfigService(configCase)
	configv1Oss, err := config.ParseOSS(context)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	ossOSS := oss.NewOSS(configv1Oss)
	fileCase := biz2.NewFileCase(ossOSS)
	fileService := base.NewFileService(fileCase)
	authentication_Jwt := config.ParseAuthnJWT(context)
	authenticator := middleware.NewAuthenticator(authentication_Jwt)
	userToken := middleware.NewUserToken(authentication_Jwt, cacheCache, authenticator)
	baseDeptRepository := data.NewBaseDeptRepository(dataData)
	baseDeptCase := biz2.NewBaseDeptCase(baseDeptRepository)
	baseRoleRepository := data.NewBaseRoleRepository(dataData)
	baseTenantRepository := data.NewBaseTenantRepository(dataData)
	baseRoleCase := biz2.NewBaseRoleCase(baseRoleRepository, baseTenantRepository)
	baseDictRepository := data.NewBaseDictRepository(dataData)
	baseDictItemRepository := data.NewBaseDictItemRepository(dataData)
	loginCase := biz2.NewLoginCase(baseCase, userToken, baseDeptCase, baseRoleCase, baseUserCase, baseTenantRepository, baseDictRepository, baseDictItemRepository)
	loginService := base.NewLoginService(loginCase)
	oAuth := config.ParseOAuth(context)
	manager, err := oauth.NewManager(oAuth)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	baseThirdAccountRepository := data.NewBaseThirdAccountRepository(dataData)
	baseThirdAccountCase := biz2.NewBaseThirdAccountCase(baseThirdAccountRepository)
	userEvents := event.NewUserEvents()
	oauthCase := biz2.NewOauthCase(baseCase, transaction, manager, baseThirdAccountCase, baseUserCase, baseRoleCase, baseDeptCase, loginCase, configCase, userEvents)
	oauthService := base.NewOauthService(oauthCase)
	mcpServer, err := server.NewMCPHandler(context)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	mcpCase, err := biz2.NewMcpCase(context, baseAPIRepository, mcpServer)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	mcpService := base.NewMcpService(mcpCase)
	sseServer, err := base2.NewSSEHandler(context)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	sseRegistry := sse.NewRegistry()
	publisher := sse.NewPublisher(sseServer)
	codegenManager := codegen.NewManager()
	sseCase, err := biz2.NewSseCase(context, authenticator, userToken, sseServer, sseRegistry, publisher, codegenManager)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	sseService := base.NewSseService(sseCase)
	services := base2.Services{
		AiSession: aiSessionService,
		AiTool:    aiToolService,
		AiMessage: aiMessageService,
		Config:    configService,
		File:      fileService,
		Login:     loginService,
		Oauth:     oauthService,
		Mcp:       mcpService,
		Sse:       sseService,
	}
	basePostRepository := data.NewBasePostRepository(dataData)
	casbinRuleRepository := data.NewCasbinRuleRepository(dataData)
	baseMenuRepository := data.NewBaseMenuRepository(dataData)
	openapiRegistry, err := server.NewOpenAPIRegistry()
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	baseAPICase := biz3.NewBaseAPICase(baseCase, baseAPIRepository, authentication_Jwt, openapiRegistry)
	engine, err := middleware.NewAuthzEngine()
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	casbinRuleCase, err := biz3.NewCasbinRuleCase(casbinRuleRepository, transaction, baseMenuRepository, baseRoleRepository, baseTenantRepository, baseAPICase, engine)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	bizBaseRoleCase := biz3.NewBaseRoleCase(baseCase, transaction, baseRoleRepository, baseTenantRepository, casbinRuleCase)
	bizBaseDeptCase := biz3.NewBaseDeptCase(baseCase, baseDeptRepository)
	baseMenuCase := biz3.NewBaseMenuCase(baseCase, transaction, baseMenuRepository, baseRoleRepository, casbinRuleCase)
	bizBaseUserCase := biz3.NewBaseUserCase(baseCase, transaction, baseUserRepository, baseDeptRepository, basePostRepository, bizBaseRoleCase, bizBaseDeptCase, baseMenuCase, baseRoleCase, userEvents)
	baseTenantCase := biz3.NewBaseTenantCase(baseCase, transaction, baseTenantRepository, baseDeptRepository, baseRoleRepository, baseUserRepository, casbinRuleRepository, casbinRuleCase, userEvents)
	authCase := biz3.NewAuthCase(baseCase, bizBaseUserCase, bizBaseRoleCase, bizBaseDeptCase, baseTenantCase, baseMenuCase, fileCase)
	authService := admin.NewAuthService(authCase)
	baseApiService := admin.NewBaseApiService(baseAPICase)
	baseAreaRepository := data.NewBaseAreaRepository(dataData)
	baseAreaCase := biz3.NewBaseAreaCase(baseCase, baseAreaRepository)
	baseAreaService := admin.NewBaseAreaService(baseAreaCase)
	baseConfigCase := biz3.NewBaseConfigCase(baseCase, baseConfigRepository)
	baseConfigService := admin.NewBaseConfigService(baseConfigCase)
	baseDeptService := admin.NewBaseDeptService(bizBaseDeptCase)
	baseDictItemCase := biz3.NewBaseDictItemCase(baseCase, baseDictRepository, baseDictItemRepository)
	baseDictCase := biz3.NewBaseDictCase(baseCase, baseDictRepository, baseDictItemCase)
	baseDictService := admin.NewBaseDictService(baseDictCase, baseDictItemCase)
	baseJobRepository := data.NewBaseJobRepository(dataData)
	baseJobLogRepository := data.NewBaseJobLogRepository(dataData)
	baseJobLogCase := biz3.NewBaseJobLogCase(baseCase, baseJobLogRepository)
	taskRegistry := task.NewRegistry()
	cronServer := job.NewCronServer(baseJobRepository, taskRegistry)
	baseJobCase := biz3.NewBaseJobCase(baseCase, baseJobRepository, baseJobLogCase, cronServer)
	baseJobService := admin.NewBaseJobService(baseJobCase, baseJobLogCase)
	baseLogRepository := data.NewBaseLogRepository(dataData)
	baseLogCase := biz3.NewBaseLogCase(baseCase, baseLogRepository)
	baseLogService := admin.NewBaseLogService(baseLogCase)
	baseMenuService := admin.NewBaseMenuService(baseMenuCase)
	basePostCase := biz3.NewBasePostCase(baseCase, transaction, basePostRepository, baseUserRepository)
	basePostService := admin.NewBasePostService(basePostCase)
	baseRoleService := admin.NewBaseRoleService(bizBaseRoleCase)
	baseTenantService := admin.NewBaseTenantService(baseTenantCase)
	baseThirdAccountService := admin.NewBaseThirdAccountService(baseThirdAccountCase)
	baseUserService := admin.NewBaseUserService(bizBaseUserCase)
	codeGenTableRepository := data.NewCodeGenTableRepository(dataData)
	codeGenColumnRepository := data.NewCodeGenColumnRepository(dataData)
	codeGenColumnCase := biz3.NewCodeGenColumnCase(codeGenColumnRepository, client, transaction, baseDictRepository, codeGenTableRepository)
	codeGenProtoRepository := data.NewCodeGenProtoRepository(dataData)
	codeGenProtoCase := biz3.NewCodeGenProtoCase(codeGenProtoRepository, transaction, baseAPIRepository, codeGenTableRepository, codeGenColumnCase)
	codeGenTableCase := biz3.NewCodeGenTableCase(codeGenTableRepository, client, transaction, baseDictRepository, baseDictItemRepository, baseMenuCase, codeGenColumnCase, codeGenProtoCase)
	baseMigrationRepository := data.NewBaseMigrationRepository(dataData)
	baseMigrationCase := biz3.NewBaseMigrationCase(baseCase, baseMigrationRepository)
	codeGenCase := biz3.NewCodeGenCase(baseCase, transaction, baseAPICase, codeGenTableCase, codeGenColumnCase, codeGenProtoCase, baseMenuCase, baseMigrationCase, client, codegenManager)
	codeGenService := admin.NewCodeGenService(codeGenCase)
	codeGenColumnService := admin.NewCodeGenColumnService(codeGenColumnCase)
	codeGenProtoService := admin.NewCodeGenProtoService(codeGenProtoCase)
	codeGenTableService := admin.NewCodeGenTableService(codeGenTableCase)
	baseMigrationService := admin.NewBaseMigrationService(baseMigrationCase)
	additionalDocuments := newAdditionalProjectDocuments(additionalModules, configuredDocuments)
	catalog, err := newProjectDocumentCatalog(additionalDocuments)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	projectDocumentCase := biz3.NewProjectDocumentCase(catalog)
	projectDocumentService := admin.NewProjectDocumentService(projectDocumentCase)
	adminServices := admin2.Services{
		Auth:             authService,
		BaseAPI:          baseApiService,
		BaseArea:         baseAreaService,
		BaseConfig:       baseConfigService,
		BaseDept:         baseDeptService,
		BaseDict:         baseDictService,
		BaseJob:          baseJobService,
		BaseLog:          baseLogService,
		BaseMenu:         baseMenuService,
		BasePost:         basePostService,
		BaseRole:         baseRoleService,
		BaseTenant:       baseTenantService,
		BaseThirdAccount: baseThirdAccountService,
		BaseUser:         baseUserService,
		CodeGen:          codeGenService,
		CodeGenColumn:    codeGenColumnService,
		CodeGenProto:     codeGenProtoService,
		CodeGenTable:     codeGenTableService,
		BaseMigration:    baseMigrationService,
		ProjectDocument:  projectDocumentService,
	}
	baseUserCase2 := biz4.NewBaseUserCase(baseCase, baseUserRepository)
	bizAuthCase := biz4.NewAuthCase(baseCase, baseUserCase2, manager, userEvents)
	appAuthService := app.NewAuthService(bizAuthCase)
	bizBaseAreaCase := biz4.NewBaseAreaCase(baseCase, baseAreaRepository)
	appBaseAreaService := app.NewBaseAreaService(bizBaseAreaCase)
	bizBaseDictItemCase := biz4.NewBaseDictItemCase(baseCase, baseDictRepository, baseDictItemRepository)
	bizBaseDictCase := biz4.NewBaseDictCase(baseCase, baseDictRepository, bizBaseDictItemCase)
	appBaseDictService := app.NewBaseDictService(bizBaseDictCase)
	bizBaseMenuCase := biz4.NewBaseMenuCase(baseCase, baseMenuRepository)
	appBaseMenuService := app.NewBaseMenuService(bizBaseMenuCase)
	appServices := app2.Services{
		Auth:     appAuthService,
		BaseArea: appBaseAreaService,
		BaseDict: appBaseDictService,
		BaseMenu: appBaseMenuService,
	}
	modules := newModules(services, adminServices, appServices, additionalModules)
	httpMiddlewares := server.NewHTTPMiddleware(context, authenticator, baseUserRepository, engine, userToken, authentication_Jwt)
	grpcMiddlewares := server.NewGRPCMiddleware(context, authenticator, baseUserRepository, engine, userToken, authentication_Jwt)
	mcpToolsReady := server.NewMCPToolsReady(mcpServer, modules)
	agentToolsReady, err := server.NewAgentToolsReady(runtime, modules)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	openAPIReady, err := server.NewOpenAPIReady(context, baseAPICase, baseTenantCase, casbinRuleCase, openapiRegistry, modules)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	kratosadminRuntime, err := newRuntime(modules, httpMiddlewares, grpcMiddlewares, cronServer, openapiRegistry, baseConfigCase, projectDocumentCase, runtime, userEvents, mcpToolsReady, agentToolsReady, openAPIReady)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	kratosadminStandaloneRuntime, cleanup5, err := newStandaloneRuntime(kratosadminRuntime, queueQueue, taskRegistry, sseRegistry, publisher)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	grpcServer, err := server.NewGRPCServer(context, grpcMiddlewares, modules, mcpToolsReady, agentToolsReady)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	appInfo := config.GetAppInfo(context)
	httpServer, err := server.NewHTTPServer(context, appInfo, httpMiddlewares, modules, openapiRegistry, authenticator, userToken, mcpToolsReady, agentToolsReady, openAPIReady)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	kratosApp, err := newKratosApp(context, kratosadminStandaloneRuntime, grpcServer, httpServer)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return kratosApp, func() {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
