// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               unknown
// source: system/admin/v1/ai_provider.proto

/* eslint-disable */
import type { Status } from "../../../common/v1/enum";
import type { Empty } from "../../../google/protobuf/empty";

/** AI模型分类枚举。 */
export enum AiModelCategory {
  /** AI_MODEL_CATEGORY_UNSPECIFIED - 未指定AI模型分类。 */
  AI_MODEL_CATEGORY_UNSPECIFIED = 0,
  /** AI_MODEL_CATEGORY_CHAT - 对话模型。 */
  AI_MODEL_CATEGORY_CHAT = 1,
  /** AI_MODEL_CATEGORY_EMBEDDING - 向量模型。 */
  AI_MODEL_CATEGORY_EMBEDDING = 2,
  /** AI_MODEL_CATEGORY_RERANK - 重排序模型。 */
  AI_MODEL_CATEGORY_RERANK = 3,
  /** AI_MODEL_CATEGORY_IMAGE - 图片模型。 */
  AI_MODEL_CATEGORY_IMAGE = 4,
  /** AI_MODEL_CATEGORY_VIDEO - 视频模型。 */
  AI_MODEL_CATEGORY_VIDEO = 5,
  /** AI_MODEL_CATEGORY_AUDIO - 音频模型。 */
  AI_MODEL_CATEGORY_AUDIO = 6,
}

/** AI供应商分页查询条件。 */
export interface PageAiProviderRequest {
  /** 供应商名称 */
  name: string;
  /** 状态：枚举【Status】 */
  status?:
    | Status
    | undefined;
  /** 当前页码 */
  page_num: number;
  /** 每页行数 */
  page_size: number;
}

/** AI供应商分页响应。 */
export interface PageAiProviderResponse {
  /** 供应商列表 */
  providers: AiProvider[];
  /** 总数 */
  total: number;
}

/** 查询AI供应商请求。 */
export interface GetAiProviderRequest {
  /** 供应商ID */
  id: number;
}

/** AI供应商维护表单。 */
export interface AiProviderForm {
  /** 供应商ID */
  id: number;
  /** 供应商名称 */
  name: string;
  /** 模型API基础地址 */
  base_url: string;
  /** 模型API密钥；更新时留空表示保留现有密钥 */
  api_key: string;
  /** 是否已保存模型密钥 */
  api_key_configured: boolean;
  /** 排序值 */
  sort: number;
  /** Provider稳定标识 */
  provider: string;
  /** Provider个性化配置JSON对象 */
  config:
    | { [key: string]: any }
    | undefined;
  /** 供应商下的AI模型列表 */
  models: AiProviderModelForm[];
  /** 状态 */
  status: Status;
}

/** AI供应商模型维护表单；provider_id由所属供应商表单隐式给定。 */
export interface AiProviderModelForm {
  /** 模型ID；新增时为0 */
  id: number;
  /** 模型名称，供应商API标识 */
  model_name: string;
  /** 显示名称 */
  display_name: string;
  /** 模型分类：枚举【AiModelCategory】 */
  category: AiModelCategory;
  /** 分类个性化配置JSON对象 */
  config:
    | { [key: string]: any }
    | undefined;
  /** 排序值 */
  sort: number;
  /** 状态 */
  status: Status;
}

/** 创建AI供应商请求。 */
export interface CreateAiProviderRequest {
  /** AI供应商表单 */
  ai_provider: AiProviderForm | undefined;
}

/** 更新AI供应商请求。 */
export interface UpdateAiProviderRequest {
  /** AI供应商表单 */
  ai_provider: AiProviderForm | undefined;
}

/** 测试AI供应商模型请求。 */
export interface TestAiProviderModelsRequest {
  /** 待测试的AI供应商草稿 */
  ai_provider: AiProviderForm | undefined;
}

/** 单个AI模型连通性测试结果。 */
export interface AiProviderModelTestResult {
  /** 模型名称 */
  model_name: string;
  /** 测试是否成功 */
  success: boolean;
  /** 测试耗时毫秒 */
  duration_ms: number;
  /** 失败原因；成功时为空 */
  message: string;
}

/** 测试AI供应商全部模型响应。 */
export interface TestAiProviderModelsResponse {
  /** 模型测试结果 */
  results: AiProviderModelTestResult[];
}

/** 查询AI供应商选项请求。 */
export interface ListAiProviderOptionsRequest {
}

/** 查询AI供应商选项响应。 */
export interface ListAiProviderOptionsResponse {
  /** 已启用的AI供应商列表 */
  options: AiProviderOption[];
}

/** AI供应商选项。 */
export interface AiProviderOption {
  /** 供应商ID */
  id: number;
  /** 供应商名称 */
  name: string;
  /** Provider稳定标识 */
  provider: string;
}

/** 删除AI供应商请求。 */
export interface DeleteAiProviderRequest {
  /** 供应商ID */
  id: number;
}

/** 设置AI供应商状态请求。 */
export interface SetAiProviderStatusRequest {
  /** 供应商ID */
  id: number;
  /** 状态 */
  status: Status;
}

/** AI供应商分页记录。 */
export interface AiProvider {
  /** 供应商ID */
  id: number;
  /** 供应商名称 */
  name: string;
  /** 模型API基础地址 */
  base_url: string;
  /** 是否已保存模型密钥 */
  api_key_configured: boolean;
  /** 排序值 */
  sort: number;
  /** Provider稳定标识 */
  provider: string;
  /** 供应商下的模型名称列表 */
  model_names: string[];
  /** 状态 */
  status: Status;
  /** 创建时间 */
  created_at: string;
  /** 更新时间 */
  updated_at: string;
}

/** AI供应商管理服务。 */
export interface AiProviderService {
  /** 分页查询AI供应商。 */
  PageAiProvider(request: PageAiProviderRequest): Promise<PageAiProviderResponse>;
  /**
   * 查询已启用的AI供应商选项。
   * 字面路径必须先于 /{id} 声明：gorilla mux 按注册顺序匹配，否则会被 {id} 路由抢占。
   */
  ListAiProviderOptions(request: ListAiProviderOptionsRequest): Promise<ListAiProviderOptionsResponse>;
  /** 查询AI供应商表单。 */
  GetAiProvider(request: GetAiProviderRequest): Promise<AiProviderForm>;
  /** 创建AI供应商。 */
  CreateAiProvider(request: CreateAiProviderRequest): Promise<Empty>;
  /** 更新AI供应商。 */
  UpdateAiProvider(request: UpdateAiProviderRequest): Promise<Empty>;
  /** 测试AI供应商表单中的全部模型。 */
  TestAiProviderModels(request: TestAiProviderModelsRequest): Promise<TestAiProviderModelsResponse>;
  /** 删除AI供应商。 */
  DeleteAiProvider(request: DeleteAiProviderRequest): Promise<Empty>;
  /** 设置AI供应商状态。 */
  SetAiProviderStatus(request: SetAiProviderStatusRequest): Promise<Empty>;
}
