// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/ai_provider.proto

/* eslint-disable */
import type { Status } from "../../../common/v1/enum";
import type { Empty } from "../../../google/protobuf/empty";

/** AI供应商分页查询条件。 */
export interface PageAiProviderRequest {
  /** 供应商名称 */
  name: string;
  /** 状态：枚举【Status】 */
  status?:
    | Status
    | undefined;
  /** 当前页码 */
  page_num: number;
  /** 每页行数 */
  page_size: number;
}

/** AI供应商分页响应。 */
export interface PageAiProviderResponse {
  /** 供应商列表 */
  providers: AiProvider[];
  /** 总数 */
  total: number;
}

/** 查询AI供应商请求。 */
export interface GetAiProviderRequest {
  /** 供应商ID */
  id: number;
}

/** AI供应商维护表单。 */
export interface AiProviderForm {
  /** 供应商ID */
  id: number;
  /** 供应商名称 */
  name: string;
  /** 模型API基础地址 */
  base_url: string;
  /** 模型API密钥；更新时留空表示保留现有密钥 */
  api_key: string;
  /** 是否已保存模型密钥 */
  api_key_configured: boolean;
  /** 多模型JSON数组 */
  models_json: string;
  /** 排序值 */
  sort: number;
  /** Provider稳定标识 */
  provider: string;
  /** Provider个性化配置JSON对象 */
  config:
    | { [key: string]: any }
    | undefined;
  /** 状态 */
  status: Status;
}

/** 创建AI供应商请求。 */
export interface CreateAiProviderRequest {
  /** AI供应商表单 */
  ai_provider: AiProviderForm | undefined;
}

/** 更新AI供应商请求。 */
export interface UpdateAiProviderRequest {
  /** AI供应商表单 */
  ai_provider: AiProviderForm | undefined;
}

/** 删除AI供应商请求。 */
export interface DeleteAiProviderRequest {
  /** 供应商ID */
  id: number;
}

/** 设置AI供应商状态请求。 */
export interface SetAiProviderStatusRequest {
  /** 供应商ID */
  id: number;
  /** 状态 */
  status: Status;
}

/** AI供应商分页记录。 */
export interface AiProvider {
  /** 供应商ID */
  id: number;
  /** 供应商名称 */
  name: string;
  /** 模型API基础地址 */
  base_url: string;
  /** 是否已保存模型密钥 */
  api_key_configured: boolean;
  /** 模型名称列表 */
  model_names: string[];
  /** 排序值 */
  sort: number;
  /** Provider稳定标识 */
  provider: string;
  /** 状态 */
  status: Status;
  /** 创建时间 */
  created_at: string;
  /** 更新时间 */
  updated_at: string;
}

/** AI供应商管理服务。 */
export interface AiProviderService {
  /** 分页查询AI供应商。 */
  PageAiProvider(request: PageAiProviderRequest): Promise<PageAiProviderResponse>;
  /** 查询AI供应商表单。 */
  GetAiProvider(request: GetAiProviderRequest): Promise<AiProviderForm>;
  /** 创建AI供应商。 */
  CreateAiProvider(request: CreateAiProviderRequest): Promise<Empty>;
  /** 更新AI供应商。 */
  UpdateAiProvider(request: UpdateAiProviderRequest): Promise<Empty>;
  /** 删除AI供应商。 */
  DeleteAiProvider(request: DeleteAiProviderRequest): Promise<Empty>;
  /** 设置AI供应商状态。 */
  SetAiProviderStatus(request: SetAiProviderStatusRequest): Promise<Empty>;
}
