// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/ai_query.proto

/* eslint-disable */

/** 智能问数状态枚举。 */
export enum AiQueryStatus {
  /** AI_QUERY_STATUS_UNSPECIFIED - 未指定智能问数状态。 */
  AI_QUERY_STATUS_UNSPECIFIED = 0,
  /** AI_QUERY_STATUS_SUCCESS - 成功。 */
  AI_QUERY_STATUS_SUCCESS = 1,
  /** AI_QUERY_STATUS_FAILED - 失败。 */
  AI_QUERY_STATUS_FAILED = 2,
}

/** 智能问数分页查询条件。 */
export interface PageAiQueryRequest {
  /** 问题内容 */
  question: string;
  /** 问数状态：枚举【AiQueryStatus】 */
  status?:
    | AiQueryStatus
    | undefined;
  /** 当前页码 */
  page_num: number;
  /** 每页行数 */
  page_size: number;
}

/** 智能问数分页响应。 */
export interface PageAiQueryResponse {
  /** 智能问数记录列表 */
  queries: AiQueryRecord[];
  /** 总数 */
  total: number;
}

/** 查询智能问数记录请求。 */
export interface GetAiQueryRequest {
  /** 记录ID */
  id: number;
}

/** 智能问数结果快照行。 */
export interface AiQueryResultRow {
  /** 行数据 */
  values: string[];
}

/** 智能问数记录。 */
export interface AiQueryRecord {
  /** 记录ID */
  id: number;
  /** 租户ID */
  tenant_id: number;
  /** 用户ID */
  user_id: number;
  /** 用户账号 */
  user_name: string;
  /** 自然语言问题 */
  question: string;
  /** 生成的只读SQL */
  sql: string;
  /** 问数状态：枚举【AiQueryStatus】 */
  status: AiQueryStatus;
  /** 结果行数 */
  row_count: number;
  /** SQL执行耗时毫秒 */
  elapsed_ms: number;
  /** 失败原因 */
  error_msg: string;
  /** 结果快照列名，仅详情返回 */
  result_columns: string[];
  /** 结果快照数据行，仅详情返回 */
  result_rows: AiQueryResultRow[];
  /** 创建时间 */
  created_at: string;
}

/** 智能问数记录管理服务。 */
export interface AiQueryService {
  /** 分页查询智能问数记录。 */
  PageAiQuery(request: PageAiQueryRequest): Promise<PageAiQueryResponse>;
  /** 查询智能问数记录详情。 */
  GetAiQuery(request: GetAiQueryRequest): Promise<AiQueryRecord>;
}
