// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               unknown
// source: system/admin/v1/ai_session.proto

/* eslint-disable */
import type { AiMessageStatus } from "../../../base/v1/ai_session";
import type { Terminal } from "../../../base/v1/ai_tool";

/** AI会话分页查询条件。 */
export interface PageAiSessionRequest {
  /** 会话标题 */
  title: string;
  /** 终端类型：枚举【Terminal】 */
  terminal?:
    | Terminal
    | undefined;
  /** 当前页码 */
  page_num: number;
  /** 每页行数 */
  page_size: number;
}

/** AI会话分页响应。 */
export interface PageAiSessionResponse {
  /** 会话列表 */
  sessions: AiSessionRecord[];
  /** 总数 */
  total: number;
}

/** AI会话分页记录。 */
export interface AiSessionRecord {
  /** 会话ID */
  id: number;
  /** 所属用户ID */
  user_id: number;
  /** 用户账号 */
  user_name: string;
  /** 用户昵称 */
  nick_name: string;
  /** 会话标题 */
  title: string;
  /** 会话摘要 */
  summary: string;
  /** 终端类型：枚举【Terminal】 */
  terminal: Terminal;
  /** 消息轮次数 */
  message_count: number;
  /** 累计输入Token数 */
  input_tokens: number;
  /** 累计输出Token数 */
  output_tokens: number;
  /** 累计缓存Token数 */
  cache_tokens: number;
  /** 累计总Token数 */
  total_tokens: number;
  /** 创建时间 */
  created_at: string;
  /** 更新时间 */
  updated_at: string;
}

/** 分页查询AI会话消息请求。 */
export interface PageAiSessionMessageRequest {
  /** 会话ID */
  id: number;
  /** 当前页码 */
  page_num: number;
  /** 每页行数 */
  page_size: number;
}

/** 分页查询AI会话消息响应。 */
export interface PageAiSessionMessageResponse {
  /** 消息列表 */
  messages: AiSessionMessageRecord[];
  /** 总数 */
  total: number;
}

/** AI会话消息记录。 */
export interface AiSessionMessageRecord {
  /** 消息ID */
  id: number;
  /** 用户输入内容 */
  input_content: string;
  /** AI回复内容 */
  output_content: string;
  /** 回复使用的模型名称 */
  model: string;
  /** 消息生成状态：枚举【AiMessageStatus】 */
  status: AiMessageStatus;
  /** 输入Token数 */
  input_tokens: number;
  /** 输出Token数 */
  output_tokens: number;
  /** 缓存Token数 */
  cache_tokens: number;
  /** 总Token数 */
  total_tokens: number;
  /** 首Token耗时毫秒 */
  first_token_ms: number;
  /** 总耗时毫秒 */
  duration_ms: number;
  /** 附件列表 */
  attachments: AiSessionMessageAttachment[];
  /** 创建时间 */
  created_at: string;
}

/** AI会话消息附件。 */
export interface AiSessionMessageAttachment {
  /** 附件名称 */
  name: string;
  /** 附件大小 */
  size: number;
  /** 附件地址 */
  url: string;
  /** 附件 MIME 类型 */
  mime_type: string;
}

/** AI会话管理服务。 */
export interface AiSessionService {
  /** 分页查询AI会话。 */
  PageAiSession(request: PageAiSessionRequest): Promise<PageAiSessionResponse>;
  /** 分页查询AI会话消息。 */
  PageAiSessionMessage(request: PageAiSessionMessageRequest): Promise<PageAiSessionMessageResponse>;
}
