// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_login_policy.proto

/* eslint-disable */

/** 查询登录来源策略请求参数。 */
export interface GetBaseLoginPolicyRequest {
}

/** 更新登录来源策略请求参数。 */
export interface UpdateBaseLoginPolicyRequest {
  /** 登录来源策略 */
  policy: BaseLoginPolicy | undefined;
}

/** 登录来源策略。 */
export interface BaseLoginPolicy {
  /** 是否启用 */
  enabled: boolean;
  /** IP黑名单 */
  ip_blacklist: string[];
  /** IP白名单 */
  ip_whitelist: string[];
  /** 禁止登录时间窗口 */
  time_windows: string[];
  /** 设备黑名单 */
  device_blacklist: string[];
  /** 设备白名单 */
  device_whitelist: string[];
  /** 按租户或用户匹配的定向规则 */
  rules: BaseLoginPolicyRule[];
}

/** 登录来源定向规则。 */
export interface BaseLoginPolicyRule {
  /** 目标类型：TENANT或USER */
  target_type: string;
  /** 目标值：租户编码或用户名 */
  target_value: string;
  /** 是否启用 */
  enabled: boolean;
  /** IP黑名单 */
  ip_blacklist: string[];
  /** IP白名单 */
  ip_whitelist: string[];
  /** 禁止登录时间窗口 */
  time_windows: string[];
  /** 设备黑名单 */
  device_blacklist: string[];
  /** 设备白名单 */
  device_whitelist: string[];
}

/** Admin登录来源策略服务。 */
export interface BaseLoginPolicyService {
  /** 查询登录来源策略。 */
  GetBaseLoginPolicy(request: GetBaseLoginPolicyRequest): Promise<BaseLoginPolicy>;
  /** 更新登录来源策略。 */
  UpdateBaseLoginPolicy(request: UpdateBaseLoginPolicyRequest): Promise<BaseLoginPolicy>;
}
