// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               unknown
// source: system/admin/v1/base_api_rate_limit_policy.proto

/* eslint-disable */
import type { Status } from "../../../common/v1/enum";
import type { Empty } from "../../../google/protobuf/empty";

/** 接口限流维度。 */
export enum BaseApiRateLimitDimension {
  /** BASE_API_RATE_LIMIT_DIMENSION_UNSPECIFIED - 未指定维度。 */
  BASE_API_RATE_LIMIT_DIMENSION_UNSPECIFIED = 0,
  /** BASE_API_RATE_LIMIT_DIMENSION_GLOBAL - 全接口共享限额。 */
  BASE_API_RATE_LIMIT_DIMENSION_GLOBAL = 1,
  /** BASE_API_RATE_LIMIT_DIMENSION_IP - 按来源IP分别限额。 */
  BASE_API_RATE_LIMIT_DIMENSION_IP = 2,
  /** BASE_API_RATE_LIMIT_DIMENSION_TENANT - 按租户分别限额。 */
  BASE_API_RATE_LIMIT_DIMENSION_TENANT = 3,
  /** BASE_API_RATE_LIMIT_DIMENSION_USER - 按用户分别限额。 */
  BASE_API_RATE_LIMIT_DIMENSION_USER = 4,
  /** BASE_API_RATE_LIMIT_DIMENSION_OAUTH_CLIENT - 按OAuth客户端分别限额。 */
  BASE_API_RATE_LIMIT_DIMENSION_OAUTH_CLIENT = 5,
}

/** 接口限流策略分页查询条件。 */
export interface PageBaseApiRateLimitPolicyRequest {
  /** 接口操作 */
  operation: string;
  /** 限流维度 */
  dimension?:
    | BaseApiRateLimitDimension
    | undefined;
  /** 状态 */
  status?:
    | Status
    | undefined;
  /** 当前页码 */
  page_num: number;
  /** 每页数量 */
  page_size: number;
}

/** 接口限流策略分页响应。 */
export interface PageBaseApiRateLimitPolicyResponse {
  /** 接口限流策略列表 */
  base_api_rate_limit_policies: BaseApiRateLimitPolicy[];
  /** 总数 */
  total: number;
}

/** 接口限流策略详情查询条件。 */
export interface GetBaseApiRateLimitPolicyRequest {
  /** 策略ID */
  id: number;
}

/** 接口限流策略表单。 */
export interface BaseApiRateLimitPolicyForm {
  /** 策略ID */
  id: number;
  /** 接口操作列表 */
  operations: string[];
  /** 限流维度 */
  dimension: BaseApiRateLimitDimension;
  /** 限流规则ID */
  rule_id: number;
  /** 策略规则参数JSON */
  rule_params: string;
  /** 状态 */
  status: Status;
  /** 备注 */
  remark: string;
}

/** 创建接口限流策略请求参数。 */
export interface CreateBaseApiRateLimitPolicyRequest {
  /** 接口限流策略表单 */
  base_api_rate_limit_policy: BaseApiRateLimitPolicyForm | undefined;
}

/** 更新接口限流策略请求参数。 */
export interface UpdateBaseApiRateLimitPolicyRequest {
  /** 接口限流策略表单 */
  base_api_rate_limit_policy: BaseApiRateLimitPolicyForm | undefined;
}

/** 删除接口限流策略请求参数。 */
export interface DeleteBaseApiRateLimitPolicyRequest {
  /** 策略ID列表 */
  id: string;
}

/** 设置接口限流策略状态请求参数。 */
export interface SetBaseApiRateLimitPolicyStatusRequest {
  /** 策略ID */
  id: number;
  /** 状态 */
  status: Status;
}

/** 接口限流策略详情。 */
export interface BaseApiRateLimitPolicy {
  /** 策略ID */
  id: number;
  /** 限流接口列表 */
  apis: BaseApiRateLimitPolicyAPI[];
  /** 限流维度 */
  dimension: BaseApiRateLimitDimension;
  /** 限流规则ID */
  rule_id: number;
  /** 限流规则编码 */
  rule_code: string;
  /** 限流规则名称 */
  rule_name: string;
  /** 策略规则参数JSON */
  rule_params: string;
  /** 状态 */
  status: Status;
  /** 备注 */
  remark: string;
  /** 创建时间 */
  created_at: string;
  /** 更新时间 */
  updated_at: string;
}

/** 接口限流策略关联的接口摘要。 */
export interface BaseApiRateLimitPolicyAPI {
  /** 接口操作 */
  operation: string;
  /** 服务名称 */
  service_name: string;
  /** 服务描述 */
  service_desc: string;
  /** 请求方法 */
  method: string;
  /** 请求地址 */
  path: string;
}

/** Admin接口限流策略服务。 */
export interface BaseApiRateLimitPolicyService {
  /** 查询接口限流策略分页列表。 */
  PageBaseApiRateLimitPolicy(request: PageBaseApiRateLimitPolicyRequest): Promise<PageBaseApiRateLimitPolicyResponse>;
  /** 查询接口限流策略详情。 */
  GetBaseApiRateLimitPolicy(request: GetBaseApiRateLimitPolicyRequest): Promise<BaseApiRateLimitPolicyForm>;
  /** 创建接口限流策略。 */
  CreateBaseApiRateLimitPolicy(request: CreateBaseApiRateLimitPolicyRequest): Promise<Empty>;
  /** 更新接口限流策略。 */
  UpdateBaseApiRateLimitPolicy(request: UpdateBaseApiRateLimitPolicyRequest): Promise<Empty>;
  /** 删除接口限流策略。 */
  DeleteBaseApiRateLimitPolicy(request: DeleteBaseApiRateLimitPolicyRequest): Promise<Empty>;
  /** 设置接口限流策略状态。 */
  SetBaseApiRateLimitPolicyStatus(request: SetBaseApiRateLimitPolicyStatusRequest): Promise<Empty>;
}
