// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_translation.proto

/* eslint-disable */
import type { Empty } from "../../../google/protobuf/empty";

/** 统一翻译表目标类型，和 base_translation.target_type 的值一一对应。 */
export enum TranslationTargetType {
  /** TRANSLATION_TARGET_TYPE_UNSPECIFIED - 未指定统一翻译表目标类型。 */
  TRANSLATION_TARGET_TYPE_UNSPECIFIED = 0,
  /** TRANSLATION_TARGET_TYPE_BASE_CONFIG_VALUE - 系统配置值。 */
  TRANSLATION_TARGET_TYPE_BASE_CONFIG_VALUE = 1,
  /** TRANSLATION_TARGET_TYPE_BASE_CONFIG_NAME - 系统配置名称。 */
  TRANSLATION_TARGET_TYPE_BASE_CONFIG_NAME = 2,
  /** TRANSLATION_TARGET_TYPE_BASE_DICT - 字典名称。 */
  TRANSLATION_TARGET_TYPE_BASE_DICT = 3,
  /** TRANSLATION_TARGET_TYPE_BASE_DICT_ITEM - 字典项标签。 */
  TRANSLATION_TARGET_TYPE_BASE_DICT_ITEM = 4,
  /** TRANSLATION_TARGET_TYPE_BASE_MENU - 菜单标题。 */
  TRANSLATION_TARGET_TYPE_BASE_MENU = 5,
}

/** 翻译单个文本请求。 */
export interface DraftBaseTranslationRequest {
  /** 待翻译文本 */
  source: string;
  /** 目标语言区域，不传时翻译所有启用的非主语言 */
  locale?: string | undefined;
}

/** 翻译单个文本响应。 */
export interface DraftBaseTranslationResponse {
  /** 翻译结果 */
  translations: DraftBaseTranslationItem[];
}

/** 翻译单个文本响应。 */
export interface DraftBaseTranslationItem {
  /** 目标语言区域 */
  locale: string;
  /** 翻译文本 */
  translation: string;
}

/** 修改单个翻译信息请求。 */
export interface UpdateBaseTranslationRequest {
  /** 翻译记录ID，大于零时优先按ID更新；ID不存在时根据目标信息更新或新增 */
  id: number;
  /** 翻译目标类型，ID为零时用于查询或新增 */
  target_type: TranslationTargetType;
  /** 目标资源ID，ID为零时用于查询或新增 */
  target_id: number;
  /** 目标语言区域，ID为零时用于查询或新增 */
  locale: string;
  /** 翻译文本 */
  name: string;
}

/** 国际化翻译信息 */
export interface BaseTranslation {
  /** 翻译记录ID */
  id: number;
  /** 翻译目标类型 */
  target_type: TranslationTargetType;
  /** 目标资源ID */
  target_id: number;
  /** 语言区域 */
  locale: string;
  /** 翻译文本 */
  name: string;
}

/** 代码生成单语言国际化配置 */
export interface CodeGenLocaleConfig {
  /** 业务或字段描述 */
  comment: string;
  /** 左树描述 */
  left_tree_comment: string;
}

/** 国际化翻译信息服务。 */
export interface BaseTranslationService {
  /** 翻译单个文本。 */
  DraftBaseTranslation(request: DraftBaseTranslationRequest): Promise<DraftBaseTranslationResponse>;
  /** 修改国际化翻译信息 */
  UpdateBaseTranslation(request: UpdateBaseTranslationRequest): Promise<Empty>;
}
