// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_audit_log.proto

/* eslint-disable */

/**
 * BaseAuditResult 定义审计事件的最终处理结果。
 * SUCCESS 表示业务完成，FAILURE 表示可预期拒绝，ERROR 表示系统异常。
 */
export enum BaseAuditResult {
  /** BASE_AUDIT_RESULT_UNSPECIFIED - 未指定审计结果。 */
  BASE_AUDIT_RESULT_UNSPECIFIED = 0,
  /** BASE_AUDIT_RESULT_SUCCESS - 操作成功。 */
  BASE_AUDIT_RESULT_SUCCESS = 1,
  /** BASE_AUDIT_RESULT_FAILURE - 操作失败。 */
  BASE_AUDIT_RESULT_FAILURE = 2,
  /** BASE_AUDIT_RESULT_ERROR - 执行异常。 */
  BASE_AUDIT_RESULT_ERROR = 3,
}

/**
 * BaseLoginLogType 定义认证链路产生的登录事件类型。
 * 类型用于区分密码、OAuth、MFA、令牌刷新和退出操作的审计统计。
 */
export enum BaseLoginLogType {
  /** BASE_LOGIN_LOG_TYPE_UNSPECIFIED - 未指定登录日志类型。 */
  BASE_LOGIN_LOG_TYPE_UNSPECIFIED = 0,
  /** BASE_LOGIN_LOG_TYPE_PASSWORD - 密码登录。 */
  BASE_LOGIN_LOG_TYPE_PASSWORD = 1,
  /** BASE_LOGIN_LOG_TYPE_OAUTH - OAuth 登录。 */
  BASE_LOGIN_LOG_TYPE_OAUTH = 2,
  /** BASE_LOGIN_LOG_TYPE_MFA - 多因素认证。 */
  BASE_LOGIN_LOG_TYPE_MFA = 3,
  /** BASE_LOGIN_LOG_TYPE_TOKEN_REFRESH - 刷新访问令牌。 */
  BASE_LOGIN_LOG_TYPE_TOKEN_REFRESH = 4,
  /** BASE_LOGIN_LOG_TYPE_LOGOUT - 退出登录。 */
  BASE_LOGIN_LOG_TYPE_LOGOUT = 5,
}

/**
 * BaseOperationAction 定义管理端资源变更的业务动作。
 * 动作与资源类型组合后用于生成可检索的操作审计记录。
 */
export enum BaseOperationAction {
  /** BASE_OPERATION_ACTION_UNSPECIFIED - 未指定业务操作动作。 */
  BASE_OPERATION_ACTION_UNSPECIFIED = 0,
  /** BASE_OPERATION_ACTION_CREATE - 新增资源。 */
  BASE_OPERATION_ACTION_CREATE = 1,
  /** BASE_OPERATION_ACTION_UPDATE - 修改资源。 */
  BASE_OPERATION_ACTION_UPDATE = 2,
  /** BASE_OPERATION_ACTION_DELETE - 删除资源。 */
  BASE_OPERATION_ACTION_DELETE = 3,
  /** BASE_OPERATION_ACTION_PUBLISH - 发布资源。 */
  BASE_OPERATION_ACTION_PUBLISH = 4,
  /** BASE_OPERATION_ACTION_REVOKE - 撤回资源。 */
  BASE_OPERATION_ACTION_REVOKE = 5,
  /** BASE_OPERATION_ACTION_IMPORT - 导入数据。 */
  BASE_OPERATION_ACTION_IMPORT = 6,
  /** BASE_OPERATION_ACTION_EXPORT - 导出数据。 */
  BASE_OPERATION_ACTION_EXPORT = 7,
  /** BASE_OPERATION_ACTION_OTHER - 其他业务动作。 */
  BASE_OPERATION_ACTION_OTHER = 8,
}

/**
 * BaseDataAccessType 定义读取、导入、导出和下载等数据访问方式。
 * 该枚举只描述访问事实，不代表访问是否经过授权。
 */
export enum BaseDataAccessType {
  /** BASE_DATA_ACCESS_TYPE_UNSPECIFIED - 未指定数据访问类型。 */
  BASE_DATA_ACCESS_TYPE_UNSPECIFIED = 0,
  /** BASE_DATA_ACCESS_TYPE_LIST - 列表访问。 */
  BASE_DATA_ACCESS_TYPE_LIST = 1,
  /** BASE_DATA_ACCESS_TYPE_DETAIL - 详情访问。 */
  BASE_DATA_ACCESS_TYPE_DETAIL = 2,
  /** BASE_DATA_ACCESS_TYPE_QUERY - 条件查询。 */
  BASE_DATA_ACCESS_TYPE_QUERY = 3,
  /** BASE_DATA_ACCESS_TYPE_EXPORT - 导出数据。 */
  BASE_DATA_ACCESS_TYPE_EXPORT = 4,
  /** BASE_DATA_ACCESS_TYPE_DOWNLOAD - 下载数据。 */
  BASE_DATA_ACCESS_TYPE_DOWNLOAD = 5,
  /** BASE_DATA_ACCESS_TYPE_IMPORT - 导入数据。 */
  BASE_DATA_ACCESS_TYPE_IMPORT = 6,
}

/**
 * BasePermissionTargetType 定义权限变更所作用的安全对象类型。
 * 目标可为用户、角色、菜单、API 或租户，便于审计定位授权边界。
 */
export enum BasePermissionTargetType {
  /** BASE_PERMISSION_TARGET_TYPE_UNSPECIFIED - 未指定权限目标类型。 */
  BASE_PERMISSION_TARGET_TYPE_UNSPECIFIED = 0,
  /** BASE_PERMISSION_TARGET_TYPE_USER - 用户权限。 */
  BASE_PERMISSION_TARGET_TYPE_USER = 1,
  /** BASE_PERMISSION_TARGET_TYPE_ROLE - 角色权限。 */
  BASE_PERMISSION_TARGET_TYPE_ROLE = 2,
  /** BASE_PERMISSION_TARGET_TYPE_MENU - 菜单权限。 */
  BASE_PERMISSION_TARGET_TYPE_MENU = 3,
  /** BASE_PERMISSION_TARGET_TYPE_API - API 权限。 */
  BASE_PERMISSION_TARGET_TYPE_API = 4,
  /** BASE_PERMISSION_TARGET_TYPE_TENANT - 租户权限。 */
  BASE_PERMISSION_TARGET_TYPE_TENANT = 5,
}

/**
 * BasePermissionAction 定义安全对象及其授权关系的变更动作。
 * 授予、回收和对象增删改均应保留对应的审计上下文。
 */
export enum BasePermissionAction {
  /** BASE_PERMISSION_ACTION_UNSPECIFIED - 未指定权限动作。 */
  BASE_PERMISSION_ACTION_UNSPECIFIED = 0,
  /** BASE_PERMISSION_ACTION_GRANT - 授予权限。 */
  BASE_PERMISSION_ACTION_GRANT = 1,
  /** BASE_PERMISSION_ACTION_REVOKE - 回收权限。 */
  BASE_PERMISSION_ACTION_REVOKE = 2,
  /** BASE_PERMISSION_ACTION_CREATE - 新增权限对象。 */
  BASE_PERMISSION_ACTION_CREATE = 3,
  /** BASE_PERMISSION_ACTION_UPDATE - 修改权限对象。 */
  BASE_PERMISSION_ACTION_UPDATE = 4,
  /** BASE_PERMISSION_ACTION_DELETE - 删除权限对象。 */
  BASE_PERMISSION_ACTION_DELETE = 5,
  /** BASE_PERMISSION_ACTION_ASSIGN - 分配权限。 */
  BASE_PERMISSION_ACTION_ASSIGN = 6,
}

/**
 * BasePolicyEvaluationType 定义授权引擎执行的评估模式。
 * 评估可以针对单个资源，也可以批量过滤资源对或项目集合。
 */
export enum BasePolicyEvaluationType {
  /** BASE_POLICY_EVALUATION_TYPE_UNSPECIFIED - 未指定策略评估类型。 */
  BASE_POLICY_EVALUATION_TYPE_UNSPECIFIED = 0,
  /** BASE_POLICY_EVALUATION_TYPE_IS_AUTHORIZED - 单主体单资源鉴权。 */
  BASE_POLICY_EVALUATION_TYPE_IS_AUTHORIZED = 1,
  /** BASE_POLICY_EVALUATION_TYPE_FILTER_PAIRS - 批量资源动作过滤。 */
  BASE_POLICY_EVALUATION_TYPE_FILTER_PAIRS = 2,
  /** BASE_POLICY_EVALUATION_TYPE_FILTER_PROJECTS - 批量项目过滤。 */
  BASE_POLICY_EVALUATION_TYPE_FILTER_PROJECTS = 3,
}

/**
 * BasePolicyDecision 定义授权策略评估的决策结果。
 * ERROR 表示策略引擎未能完成可靠判断，不能按允许访问处理。
 */
export enum BasePolicyDecision {
  /** BASE_POLICY_DECISION_UNSPECIFIED - 未指定策略决策结果。 */
  BASE_POLICY_DECISION_UNSPECIFIED = 0,
  /** BASE_POLICY_DECISION_ALLOW - 允许访问。 */
  BASE_POLICY_DECISION_ALLOW = 1,
  /** BASE_POLICY_DECISION_DENY - 拒绝访问。 */
  BASE_POLICY_DECISION_DENY = 2,
  /** BASE_POLICY_DECISION_ERROR - 策略引擎异常。 */
  BASE_POLICY_DECISION_ERROR = 3,
}

/** 登录日志分页查询条件。 */
export interface PageBaseLoginLogRequest {
  /** 租户ID */
  tenant_id?:
    | number
    | undefined;
  /** 用户ID */
  user_id?:
    | number
    | undefined;
  /** 登录类型 */
  login_type?:
    | BaseLoginLogType
    | undefined;
  /** 结果 */
  result?:
    | BaseAuditResult
    | undefined;
  /** 事件时间 */
  occurred_at: string[];
  /** 关键字 */
  keyword: string;
  /** 当前页码 */
  page_num: number;
  /** 每页行数 */
  page_size: number;
}

/** 登录日志分页响应。 */
export interface PageBaseLoginLogResponse {
  /** 登录日志列表 */
  base_login_logs: BaseLoginLog[];
  /** 总数 */
  total: number;
}

/** 查询登录日志详情请求。 */
export interface GetBaseLoginLogRequest {
  /** 登录日志ID */
  id: number;
}

/** 登录日志。 */
export interface BaseLoginLog {
  /** 登录日志ID */
  id: number;
  /** 租户ID */
  tenant_id: number;
  /** 租户编码 */
  tenant_code: string;
  /** 用户ID */
  user_id: number;
  /** 账号名 */
  user_name: string;
  /** 登录类型 */
  login_type: BaseLoginLogType;
  /** 结果 */
  result: BaseAuditResult;
  /** 原因编码 */
  reason_code: string;
  /** 原因说明 */
  reason: string;
  /** 客户端IP */
  client_ip: string;
  /** 用户代理 */
  user_agent: string;
  /** 设备标识 */
  device_id: string;
  /** 请求ID */
  request_id: string;
  /** 链路追踪ID */
  trace_id: string;
  /** 事件发生时间 */
  occurred_at: string;
  /** 日志创建时间 */
  created_at: string;
}

/** API 访问日志分页查询条件。 */
export interface PageBaseApiLogRequest {
  /** 租户ID */
  tenant_id?:
    | number
    | undefined;
  /** 用户ID */
  user_id?:
    | number
    | undefined;
  /** 结果 */
  result?:
    | BaseAuditResult
    | undefined;
  /** 事件时间 */
  occurred_at: string[];
  /** 关键字 */
  keyword: string;
  /** 当前页码 */
  page_num: number;
  /** 每页行数 */
  page_size: number;
}

/** API 访问日志分页响应。 */
export interface PageBaseApiLogResponse {
  /** API访问日志列表 */
  base_api_logs: BaseApiLog[];
  /** 总数 */
  total: number;
}

/** 查询 API 访问日志详情请求。 */
export interface GetBaseApiLogRequest {
  /** API日志ID */
  id: number;
}

/** API 访问日志。 */
export interface BaseApiLog {
  /** API日志ID */
  id: number;
  /** 租户ID */
  tenant_id: number;
  /** 租户编码 */
  tenant_code: string;
  /** 用户ID */
  user_id: number;
  /** 用户名称 */
  user_name: string;
  /** 请求ID */
  request_id: string;
  /** 链路追踪ID */
  trace_id: string;
  /** 服务名 */
  service_name: string;
  /** 操作方法 */
  operation: string;
  /** 请求方法 */
  method: string;
  /** 请求路径 */
  path: string;
  /** 状态码 */
  status_code: number;
  /** 结果 */
  result: BaseAuditResult;
  /** 原因编码 */
  reason_code: string;
  /** 原因说明 */
  reason: string;
  /** 耗时毫秒 */
  latency_ms: number;
  /** 请求大小 */
  request_size: number;
  /** 响应大小 */
  response_size: number;
  /** 客户端IP */
  client_ip: string;
  /** 用户代理 */
  user_agent: string;
  /** 事件发生时间 */
  occurred_at: string;
  /** 日志创建时间 */
  created_at: string;
}

/** 业务操作日志分页查询条件。 */
export interface PageBaseOperationLogRequest {
  /** 租户ID */
  tenant_id?:
    | number
    | undefined;
  /** 用户ID */
  user_id?:
    | number
    | undefined;
  /** 操作动作 */
  action?:
    | BaseOperationAction
    | undefined;
  /** 结果 */
  result?:
    | BaseAuditResult
    | undefined;
  /** 事件时间 */
  occurred_at: string[];
  /** 资源类型 */
  resource_type: string;
  /** 关键字 */
  keyword: string;
  /** 当前页码 */
  page_num: number;
  /** 每页行数 */
  page_size: number;
}

/** 业务操作日志分页响应。 */
export interface PageBaseOperationLogResponse {
  /** 业务操作日志列表 */
  base_operation_logs: BaseOperationLog[];
  /** 总数 */
  total: number;
}

/** 查询业务操作日志详情请求。 */
export interface GetBaseOperationLogRequest {
  /** 操作日志ID */
  id: number;
}

/** 业务操作日志。 */
export interface BaseOperationLog {
  /** 操作日志ID */
  id: number;
  /** 租户ID */
  tenant_id: number;
  /** 租户编码 */
  tenant_code: string;
  /** 用户ID */
  user_id: number;
  /** 用户名称 */
  user_name: string;
  /** 请求ID */
  request_id: string;
  /** 链路追踪ID */
  trace_id: string;
  /** 资源类型 */
  resource_type: string;
  /** 资源ID */
  resource_id: string;
  /** 资源名称 */
  resource_name: string;
  /** 操作动作 */
  action: BaseOperationAction;
  /** 变更字段 */
  changed_fields: string;
  /** 变更前数据 */
  before_data: string;
  /** 变更后数据 */
  after_data: string;
  /** 结果 */
  result: BaseAuditResult;
  /** 原因编码 */
  reason_code: string;
  /** 原因说明 */
  reason: string;
  /** 事件发生时间 */
  occurred_at: string;
  /** 日志创建时间 */
  created_at: string;
}

/** 数据访问日志分页查询条件。 */
export interface PageBaseDataAccessLogRequest {
  /** 租户ID */
  tenant_id?:
    | number
    | undefined;
  /** 用户ID */
  user_id?:
    | number
    | undefined;
  /** 访问类型 */
  access_type?:
    | BaseDataAccessType
    | undefined;
  /** 是否敏感数据 */
  sensitive?:
    | boolean
    | undefined;
  /** 结果 */
  result?:
    | BaseAuditResult
    | undefined;
  /** 事件时间 */
  occurred_at: string[];
  /** 资源类型 */
  resource_type: string;
  /** 关键字 */
  keyword: string;
  /** 当前页码 */
  page_num: number;
  /** 每页行数 */
  page_size: number;
}

/** 数据访问日志分页响应。 */
export interface PageBaseDataAccessLogResponse {
  /** 数据访问日志列表 */
  base_data_access_logs: BaseDataAccessLog[];
  /** 总数 */
  total: number;
}

/** 查询数据访问日志详情请求。 */
export interface GetBaseDataAccessLogRequest {
  /** 数据访问日志ID */
  id: number;
}

/** 数据访问日志。 */
export interface BaseDataAccessLog {
  /** 数据访问日志ID */
  id: number;
  /** 租户ID */
  tenant_id: number;
  /** 租户编码 */
  tenant_code: string;
  /** 用户ID */
  user_id: number;
  /** 用户名称 */
  user_name: string;
  /** 请求ID */
  request_id: string;
  /** 链路追踪ID */
  trace_id: string;
  /** 资源类型 */
  resource_type: string;
  /** 资源ID */
  resource_id: string;
  /** 访问类型 */
  access_type: BaseDataAccessType;
  /** 数据源 */
  data_source: string;
  /** 数据表名 */
  table_name: string;
  /** 访问字段范围 */
  field_scope: string;
  /** 数据范围 */
  data_scope: string;
  /** 影响行数 */
  affected_rows: number;
  /** 是否敏感数据 */
  sensitive: boolean;
  /** 脱敏SQL */
  sql_text: string;
  /** SQL指纹 */
  sql_digest: string;
  /** 结果 */
  result: BaseAuditResult;
  /** 原因编码 */
  reason_code: string;
  /** 耗时毫秒 */
  latency_ms: number;
  /** 事件发生时间 */
  occurred_at: string;
  /** 日志创建时间 */
  created_at: string;
}

/** 权限日志分页查询条件。 */
export interface PageBasePermissionLogRequest {
  /** 租户ID */
  tenant_id?:
    | number
    | undefined;
  /** 用户ID */
  user_id?:
    | number
    | undefined;
  /** 目标类型 */
  target_type?:
    | BasePermissionTargetType
    | undefined;
  /** 权限动作 */
  action?:
    | BasePermissionAction
    | undefined;
  /** 结果 */
  result?:
    | BaseAuditResult
    | undefined;
  /** 事件时间 */
  occurred_at: string[];
  /** 关键字 */
  keyword: string;
  /** 当前页码 */
  page_num: number;
  /** 每页行数 */
  page_size: number;
}

/** 权限日志分页响应。 */
export interface PageBasePermissionLogResponse {
  /** 权限日志列表 */
  base_permission_logs: BasePermissionLog[];
  /** 总数 */
  total: number;
}

/** 查询权限日志详情请求。 */
export interface GetBasePermissionLogRequest {
  /** 权限日志ID */
  id: number;
}

/** 权限日志。 */
export interface BasePermissionLog {
  /** 权限日志ID */
  id: number;
  /** 租户ID */
  tenant_id: number;
  /** 租户编码 */
  tenant_code: string;
  /** 用户ID */
  user_id: number;
  /** 用户名称 */
  user_name: string;
  /** 请求ID */
  request_id: string;
  /** 链路追踪ID */
  trace_id: string;
  /** 目标类型 */
  target_type: BasePermissionTargetType;
  /** 目标ID */
  target_id: string;
  /** 目标名称 */
  target_name: string;
  /** 权限动作 */
  action: BasePermissionAction;
  /** 变更前权限 */
  old_value: string;
  /** 变更后权限 */
  new_value: string;
  /** 结果 */
  result: BaseAuditResult;
  /** 原因编码 */
  reason_code: string;
  /** 原因说明 */
  reason: string;
  /** 事件发生时间 */
  occurred_at: string;
  /** 日志创建时间 */
  created_at: string;
}

/** 策略评估日志分页查询条件。 */
export interface PageBasePolicyEvaluationLogRequest {
  /** 租户ID */
  tenant_id?:
    | number
    | undefined;
  /** 用户ID */
  user_id?:
    | number
    | undefined;
  /** 评估类型 */
  evaluation_type?:
    | BasePolicyEvaluationType
    | undefined;
  /** 决策结果 */
  decision?:
    | BasePolicyDecision
    | undefined;
  /** 事件时间 */
  occurred_at: string[];
  /** 资源 */
  resource: string;
  /** 关键字 */
  keyword: string;
  /** 当前页码 */
  page_num: number;
  /** 每页行数 */
  page_size: number;
}

/** 策略评估日志分页响应。 */
export interface PageBasePolicyEvaluationLogResponse {
  /** 策略评估日志列表 */
  base_policy_evaluation_logs: BasePolicyEvaluationLog[];
  /** 总数 */
  total: number;
}

/** 查询策略评估日志详情请求。 */
export interface GetBasePolicyEvaluationLogRequest {
  /** 策略评估日志ID */
  id: number;
}

/** 策略评估日志。 */
export interface BasePolicyEvaluationLog {
  /** 策略评估日志ID */
  id: number;
  /** 租户ID */
  tenant_id: number;
  /** 租户编码 */
  tenant_code: string;
  /** 用户ID */
  user_id: number;
  /** 用户名称 */
  user_name: string;
  /** 角色ID */
  role_id: number;
  /** 角色编码 */
  role_code: string;
  /** 请求ID */
  request_id: string;
  /** 链路追踪ID */
  trace_id: string;
  /** 客户端IP */
  client_ip: string;
  /** 鉴权引擎 */
  engine: string;
  /** 评估类型 */
  evaluation_type: BasePolicyEvaluationType;
  /** 资源 */
  resource: string;
  /** 动作 */
  action: string;
  /** 项目范围 */
  project: string;
  /** 决策结果 */
  decision: BasePolicyDecision;
  /** 原因编码 */
  reason_code: string;
  /** 原因说明 */
  reason: string;
  /** 评估耗时毫秒 */
  duration_ms: number;
  /** 候选数量 */
  candidate_count: number;
  /** 命中数量 */
  matched_count: number;
  /** 输入摘要 */
  input_hash: string;
  /** 事件发生时间 */
  occurred_at: string;
  /** 日志创建时间 */
  created_at: string;
}

/** 登录日志服务。 */
export interface BaseLoginLogService {
  /** 分页查询登录日志。 */
  PageBaseLoginLog(request: PageBaseLoginLogRequest): Promise<PageBaseLoginLogResponse>;
  /** 查询登录日志详情。 */
  GetBaseLoginLog(request: GetBaseLoginLogRequest): Promise<BaseLoginLog>;
}

/** API 访问日志服务。 */
export interface BaseApiLogService {
  /** 分页查询 API 访问日志。 */
  PageBaseApiLog(request: PageBaseApiLogRequest): Promise<PageBaseApiLogResponse>;
  /** 查询 API 访问日志详情。 */
  GetBaseApiLog(request: GetBaseApiLogRequest): Promise<BaseApiLog>;
}

/** 业务操作日志服务。 */
export interface BaseOperationLogService {
  /** 分页查询业务操作日志。 */
  PageBaseOperationLog(request: PageBaseOperationLogRequest): Promise<PageBaseOperationLogResponse>;
  /** 查询业务操作日志详情。 */
  GetBaseOperationLog(request: GetBaseOperationLogRequest): Promise<BaseOperationLog>;
}

/** 数据访问日志服务。 */
export interface BaseDataAccessLogService {
  /** 分页查询数据访问日志。 */
  PageBaseDataAccessLog(request: PageBaseDataAccessLogRequest): Promise<PageBaseDataAccessLogResponse>;
  /** 查询数据访问日志详情。 */
  GetBaseDataAccessLog(request: GetBaseDataAccessLogRequest): Promise<BaseDataAccessLog>;
}

/** 权限日志服务。 */
export interface BasePermissionLogService {
  /** 分页查询权限日志。 */
  PageBasePermissionLog(request: PageBasePermissionLogRequest): Promise<PageBasePermissionLogResponse>;
  /** 查询权限日志详情。 */
  GetBasePermissionLog(request: GetBasePermissionLogRequest): Promise<BasePermissionLog>;
}

/** 策略评估日志服务。 */
export interface BasePolicyEvaluationLogService {
  /** 分页查询策略评估日志。 */
  PageBasePolicyEvaluationLog(
    request: PageBasePolicyEvaluationLogRequest,
  ): Promise<PageBasePolicyEvaluationLogResponse>;
  /** 查询策略评估日志详情。 */
  GetBasePolicyEvaluationLog(request: GetBasePolicyEvaluationLogRequest): Promise<BasePolicyEvaluationLog>;
}
