// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               unknown
// source: system/admin/v1/base_message_template.proto

/* eslint-disable */
import type { MessageContentFormat } from "../../../base/v1/notification";
import type { Empty } from "../../../google/protobuf/empty";

/** 消息 Provider 模板分页查询条件。 */
export interface PageBaseMessageTemplateRequest {
  /** 消息分类ID */
  category_id?:
    | number
    | undefined;
  /** 消息 Provider ID */
  provider_id?:
    | number
    | undefined;
  /** 当前页码 */
  page_num: number;
  /** 每页数量 */
  page_size: number;
}

/** 消息 Provider 模板分页响应。 */
export interface PageBaseMessageTemplateResponse {
  /** 消息 Provider 模板列表 */
  base_message_templates: BaseMessageTemplate[];
  /** 总数 */
  total: number;
}

/** 消息 Provider 模板详情查询条件。 */
export interface GetBaseMessageTemplateRequest {
  /** 消息模板ID */
  id: number;
}

/** 创建消息 Provider 模板请求。 */
export interface CreateBaseMessageTemplateRequest {
  /** 消息 Provider 模板表单 */
  base_message_template: BaseMessageTemplateForm | undefined;
}

/** 更新消息 Provider 模板请求。 */
export interface UpdateBaseMessageTemplateRequest {
  /** 消息 Provider 模板表单 */
  base_message_template: BaseMessageTemplateForm | undefined;
}

/** 删除消息 Provider 模板请求。 */
export interface DeleteBaseMessageTemplateRequest {
  /** 消息模板ID列表 */
  id: string;
}

/** 消息 Provider 模板表单。 */
export interface BaseMessageTemplateForm {
  /** 消息模板ID */
  id: number;
  /** 消息分类ID */
  category_id: number;
  /** 消息 Provider ID */
  provider_id: number;
  /** 模板标题 */
  title: string;
  /** 模板正文 */
  content: string;
  /** 正文格式 */
  content_format: MessageContentFormat;
  /** Provider模板扩展配置JSON对象 */
  config: { [key: string]: any } | undefined;
}

/** 消息 Provider 模板。 */
export interface BaseMessageTemplate {
  /** 消息模板ID */
  id: number;
  /** 消息分类ID */
  category_id: number;
  /** 消息分类名称 */
  category_name: string;
  /** 消息 Provider ID */
  provider_id: number;
  /** 消息 Provider 名称 */
  provider_name: string;
  /** 模板标题 */
  title: string;
  /** 模板正文 */
  content: string;
  /** 正文格式 */
  content_format: MessageContentFormat;
  /** Provider模板扩展配置JSON对象 */
  config:
    | { [key: string]: any }
    | undefined;
  /** 创建时间 */
  created_at: string;
  /** 更新时间 */
  updated_at: string;
}

/** Admin消息 Provider 模板管理服务。 */
export interface BaseMessageTemplateService {
  /** 分页查询消息 Provider 模板。 */
  PageBaseMessageTemplate(request: PageBaseMessageTemplateRequest): Promise<PageBaseMessageTemplateResponse>;
  /** 查询消息 Provider 模板详情。 */
  GetBaseMessageTemplate(request: GetBaseMessageTemplateRequest): Promise<BaseMessageTemplateForm>;
  /** 创建消息 Provider 模板。 */
  CreateBaseMessageTemplate(request: CreateBaseMessageTemplateRequest): Promise<Empty>;
  /** 更新消息 Provider 模板。 */
  UpdateBaseMessageTemplate(request: UpdateBaseMessageTemplateRequest): Promise<Empty>;
  /** 删除消息 Provider 模板。 */
  DeleteBaseMessageTemplate(request: DeleteBaseMessageTemplateRequest): Promise<Empty>;
}
