// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_redact_field.proto

/* eslint-disable */
import type { SelectOptionResponse } from "../../../common/v1/common";
import type { Status } from "../../../common/v1/enum";
import type { Empty } from "../../../google/protobuf/empty";
import type { BaseRedactDirection } from "./base_redact_common";

/** 字段数据库存储方式。 */
export enum BaseRedactStorageMode {
  /** BASE_REDACT_STORAGE_MODE_UNSPECIFIED - 未配置存储方式，服务端拒绝启用字段存储保护。 */
  BASE_REDACT_STORAGE_MODE_UNSPECIFIED = 0,
  /** BASE_REDACT_STORAGE_MODE_PLAIN - 主表保存明文。 */
  BASE_REDACT_STORAGE_MODE_PLAIN = 1,
  /** BASE_REDACT_STORAGE_MODE_MASK - 主表保存脱敏值，旁表保存加密原文。 */
  BASE_REDACT_STORAGE_MODE_MASK = 2,
  /** BASE_REDACT_STORAGE_MODE_HASH - 主表保存不可逆哈希。 */
  BASE_REDACT_STORAGE_MODE_HASH = 3,
}

/** 敏感字段查询方式。 */
export enum BaseRedactSearchMode {
  /** BASE_REDACT_SEARCH_MODE_UNSPECIFIED - 未配置查询方式。 */
  BASE_REDACT_SEARCH_MODE_UNSPECIFIED = 0,
  /** BASE_REDACT_SEARCH_MODE_NONE - 不支持敏感字段查询。 */
  BASE_REDACT_SEARCH_MODE_NONE = 1,
  /** BASE_REDACT_SEARCH_MODE_DIGEST - 使用 HMAC 摘要进行精确查询。 */
  BASE_REDACT_SEARCH_MODE_DIGEST = 2,
}

/** 脱敏字段选项查询条件。 */
export interface OptionBaseRedactFieldRequest {
  /** 字段关键字 */
  keyword: string;
  /** 接口操作 */
  operation: string;
  /** 脱敏方向 */
  direction?: BaseRedactDirection | undefined;
}

/** 脱敏字段分页查询条件。 */
export interface PageBaseRedactFieldRequest {
  /** Proto消息完整名称 */
  message_ref: string;
  /** 字段路径 */
  field_path: string;
  /** 敏感字段类型 */
  sensitivity_type: string;
  /** 字段来源 */
  source: string;
  /** 状态 */
  status?:
    | Status
    | undefined;
  /** 当前页码 */
  page_num: number;
  /** 每页数量 */
  page_size: number;
}

/** 脱敏字段分页响应。 */
export interface PageBaseRedactFieldResponse {
  /** 字段列表 */
  base_redact_fields: BaseRedactField[];
  /** 总数 */
  total: number;
}

/** 脱敏字段详情查询条件。 */
export interface GetBaseRedactFieldRequest {
  id: number;
}

/** 脱敏字段表单。 */
export interface BaseRedactFieldForm {
  /** 字段目录ID */
  id: number;
  /** Proto消息完整名称 */
  message_ref: string;
  /** 字段路径 */
  field_path: string;
  /** Proto字段类型 */
  field_kind: string;
  /** 敏感字段类型 */
  sensitivity_type: string;
  /** 字段来源 */
  source: string;
  /** 数据实体标识 */
  entity_ref: string;
  /** 数据库表名 */
  table_name: string;
  /** 数据库字段名 */
  column_name: string;
  /** 业务主键字段 */
  record_key_field: string;
  /** 数据库存储方式 */
  storage_mode: BaseRedactStorageMode;
  /** 存储脱敏规则ID */
  storage_rule_id: number;
  /** 敏感字段查询方式 */
  search_mode: BaseRedactSearchMode;
  /** 状态 */
  status: Status;
  /** 备注 */
  remark: string;
}

/** 更新脱敏字段请求参数。 */
export interface UpdateBaseRedactFieldRequest {
  base_redact_field: BaseRedactFieldForm | undefined;
}

/** 删除脱敏字段请求参数。 */
export interface DeleteBaseRedactFieldRequest {
  id: string;
}

/** 设置脱敏字段状态请求参数。 */
export interface SetBaseRedactFieldStatusRequest {
  /** 字段目录ID */
  id: number;
  /** 状态 */
  status: Status;
}

/** 脱敏字段目录。 */
export interface BaseRedactField {
  /** 字段目录ID */
  id: number;
  /** Proto消息完整名称 */
  message_ref: string;
  /** 字段路径 */
  field_path: string;
  /** Proto字段类型 */
  field_kind: string;
  /** 敏感字段类型 */
  sensitivity_type: string;
  /** 字段来源 */
  source: string;
  /** 数据实体标识 */
  entity_ref: string;
  /** 数据库表名 */
  table_name: string;
  /** 数据库字段名 */
  column_name: string;
  /** 业务主键字段 */
  record_key_field: string;
  /** 数据库存储方式 */
  storage_mode: BaseRedactStorageMode;
  /** 存储脱敏规则ID */
  storage_rule_id: number;
  /** 敏感字段查询方式 */
  search_mode: BaseRedactSearchMode;
  /** 状态 */
  status: Status;
  /** 备注 */
  remark: string;
  /** 创建时间 */
  created_at: string;
  /** 更新时间 */
  updated_at: string;
}

/** Admin脱敏字段目录服务。 */
export interface BaseRedactFieldService {
  /** 查询脱敏字段选项。 */
  OptionBaseRedactField(request: OptionBaseRedactFieldRequest): Promise<SelectOptionResponse>;
  /** 查询脱敏字段分页列表。 */
  PageBaseRedactField(request: PageBaseRedactFieldRequest): Promise<PageBaseRedactFieldResponse>;
  /** 查询脱敏字段详情。 */
  GetBaseRedactField(request: GetBaseRedactFieldRequest): Promise<BaseRedactFieldForm>;
  /** 更新脱敏字段。 */
  UpdateBaseRedactField(request: UpdateBaseRedactFieldRequest): Promise<Empty>;
  /** 删除脱敏字段。 */
  DeleteBaseRedactField(request: DeleteBaseRedactFieldRequest): Promise<Empty>;
  /** 设置脱敏字段状态。 */
  SetBaseRedactFieldStatus(request: SetBaseRedactFieldStatusRequest): Promise<Empty>;
}
