// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               unknown
// source: system/admin/v1/base_message_provider.proto

/* eslint-disable */
import type { SelectOptionResponse } from "../../../common/v1/common";
import type { Status } from "../../../common/v1/enum";
import type { Empty } from "../../../google/protobuf/empty";

/** 消息发送 Provider 选项查询条件。 */
export interface OptionBaseMessageProviderRequest {
}

/** 消息发送 Provider 分页查询条件。 */
export interface PageBaseMessageProviderRequest {
  /** Provider标识 */
  provider?:
    | string
    | undefined;
  /** Provider名称 */
  name?:
    | string
    | undefined;
  /** 状态 */
  status?:
    | Status
    | undefined;
  /** 当前页码 */
  page_num: number;
  /** 每页数量 */
  page_size: number;
}

/** 消息发送 Provider 分页响应。 */
export interface PageBaseMessageProviderResponse {
  /** 消息发送 Provider 列表 */
  base_message_providers: BaseMessageProvider[];
  /** 总数 */
  total: number;
}

/** 消息发送 Provider 详情查询条件。 */
export interface GetBaseMessageProviderRequest {
  /** 消息 Provider ID */
  id: number;
}

/** 创建消息发送 Provider 请求。 */
export interface CreateBaseMessageProviderRequest {
  /** 消息发送 Provider 表单 */
  base_message_provider: BaseMessageProviderForm | undefined;
}

/** 更新消息发送 Provider 请求。 */
export interface UpdateBaseMessageProviderRequest {
  /** 消息发送 Provider 表单 */
  base_message_provider: BaseMessageProviderForm | undefined;
}

/** 删除消息发送 Provider 请求。 */
export interface DeleteBaseMessageProviderRequest {
  /** 消息 Provider ID列表 */
  id: string;
}

/** 设置消息发送 Provider 状态请求。 */
export interface SetBaseMessageProviderStatusRequest {
  /** 消息 Provider ID */
  id: number;
  /** 状态 */
  status: Status;
}

/** 消息发送 Provider 表单。 */
export interface BaseMessageProviderForm {
  /** 消息 Provider ID */
  id: number;
  /** Provider稳定标识 */
  provider: string;
  /** Provider名称 */
  name: string;
  /** Provider说明 */
  description: string;
  /** 图标键或图片地址 */
  icon: string;
  /** 通用凭证标识 */
  client_id: string;
  /** 通用凭证密钥，更新时留空表示不修改 */
  client_secret: string;
  /** 是否已配置通用凭证密钥 */
  secret_configured: boolean;
  /** Provider扩展配置JSON对象 */
  config:
    | { [key: string]: any }
    | undefined;
  /** 排序 */
  sort: number;
  /** 状态 */
  status: Status;
}

/** 消息发送 Provider。 */
export interface BaseMessageProvider {
  /** 消息 Provider ID */
  id: number;
  /** Provider稳定标识 */
  provider: string;
  /** Provider名称 */
  name: string;
  /** Provider说明 */
  description: string;
  /** 图标键或图片地址 */
  icon: string;
  /** 通用凭证标识 */
  client_id: string;
  /** Provider扩展配置JSON对象 */
  config:
    | { [key: string]: any }
    | undefined;
  /** 排序 */
  sort: number;
  /** 状态 */
  status: Status;
  /** 是否已配置通用凭证密钥 */
  secret_configured: boolean;
  /** 创建时间 */
  created_at: string;
  /** 更新时间 */
  updated_at: string;
}

/** Admin消息发送 Provider 管理服务。 */
export interface BaseMessageProviderService {
  /** 查询消息发送 Provider 选项。 */
  OptionBaseMessageProvider(request: OptionBaseMessageProviderRequest): Promise<SelectOptionResponse>;
  /** 分页查询消息发送 Provider。 */
  PageBaseMessageProvider(request: PageBaseMessageProviderRequest): Promise<PageBaseMessageProviderResponse>;
  /** 查询消息发送 Provider 详情。 */
  GetBaseMessageProvider(request: GetBaseMessageProviderRequest): Promise<BaseMessageProviderForm>;
  /** 创建消息发送 Provider。 */
  CreateBaseMessageProvider(request: CreateBaseMessageProviderRequest): Promise<Empty>;
  /** 更新消息发送 Provider。 */
  UpdateBaseMessageProvider(request: UpdateBaseMessageProviderRequest): Promise<Empty>;
  /** 删除消息发送 Provider。 */
  DeleteBaseMessageProvider(request: DeleteBaseMessageProviderRequest): Promise<Empty>;
  /** 设置消息发送 Provider 状态。 */
  SetBaseMessageProviderStatus(request: SetBaseMessageProviderStatusRequest): Promise<Empty>;
}
