// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_translation.proto

/* eslint-disable */

/** 翻译状态 */
export enum TranslationStatus {
  TRANSLATION_STATUS_UNSPECIFIED = 0,
  TRANSLATION_STATUS_PENDING = 1,
  TRANSLATION_STATUS_MACHINE = 2,
  TRANSLATION_STATUS_REVIEWED = 3,
}

/** 翻译资源类型 */
export enum TranslationResourceType {
  TRANSLATION_RESOURCE_TYPE_UNSPECIFIED = 0,
  TRANSLATION_RESOURCE_TYPE_MENU = 1,
  TRANSLATION_RESOURCE_TYPE_DICT = 2,
  TRANSLATION_RESOURCE_TYPE_DICT_ITEM = 3,
  TRANSLATION_RESOURCE_TYPE_CONFIG = 4,
}

/** 系统配置翻译字段 */
export enum BaseConfigTranslationField {
  BASE_CONFIG_TRANSLATION_FIELD_UNSPECIFIED = 0,
  BASE_CONFIG_TRANSLATION_FIELD_NAME = 1,
  BASE_CONFIG_TRANSLATION_FIELD_VALUE = 2,
}

/** 生成翻译草稿请求 */
export interface GenerateTranslationDraftRequest {
  /** 资源类型 */
  resource_type: TranslationResourceType;
  /** 已保存资源ID */
  resource_id: number;
  /** 目标语言区域，仅支持en-US和ja-JP */
  target_locale: string;
  /** 系统配置翻译字段，配置资源必填 */
  field: BaseConfigTranslationField;
}

/** 生成翻译草稿响应 */
export interface GenerateTranslationDraftResponse {
  /** 资源类型 */
  resource_type: TranslationResourceType;
  /** 资源ID */
  resource_id: number;
  /** 语言区域 */
  locale: string;
  /** 机器翻译草稿 */
  translation: string;
  /** 翻译状态 */
  translation_status: TranslationStatus;
  /** 中文源文SHA-256 */
  source_hash: string;
  /** 机器翻译提供方 */
  translation_provider: string;
  /** 最近机器翻译时间 */
  translated_at: string;
  /** 系统配置翻译字段 */
  field: BaseConfigTranslationField;
}

/** 系统配置单语言翻译 */
export interface BaseConfigTranslation {
  /** 翻译记录ID */
  id: number;
  /** 系统配置ID */
  config_id: number;
  /** 语言区域 */
  locale: string;
  /** 翻译字段：name或value */
  field: BaseConfigTranslationField;
  /** 翻译文本 */
  text: string;
  /** 翻译审核状态 */
  translation_status: TranslationStatus;
  /** 中文源文SHA-256 */
  source_hash: string;
  /** 中文源文是否已变化 */
  source_changed: boolean;
  /** 机器翻译提供方 */
  translation_provider: string;
  /** 最近机器翻译时间 */
  translated_at: string;
  /** 审核人ID */
  reviewed_by: number;
  /** 审核时间 */
  reviewed_at: string;
  /** 创建人ID */
  created_by: number;
  /** 更新人ID */
  updated_by: number;
  /** 创建时间 */
  created_at: string;
  /** 更新时间 */
  updated_at: string;
  /** 删除时间 */
  deleted_at: number;
}

/** 代码生成单语言国际化配置 */
export interface CodeGenLocaleConfig {
  /** 业务或字段描述 */
  comment: string;
  /** 左树描述 */
  left_tree_comment: string;
}

/** Admin翻译草稿服务 */
export interface BaseTranslationService {
  /** 为单个已保存资源生成机器翻译草稿 */
  GenerateTranslationDraft(request: GenerateTranslationDraftRequest): Promise<GenerateTranslationDraftResponse>;
}
