// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_session.proto

/* eslint-disable */
import type { Empty } from "../../../google/protobuf/empty";

/** 查询当前会话请求参数。 */
export interface GetCurrentBaseSessionRequest {
}

/** 撤销全部会话请求参数。 */
export interface RevokeAllBaseSessionsRequest {
}

/** 当前会话信息。 */
export interface BaseSession {
  /** 用户ID */
  user_id: number;
  /** 用户账号 */
  user_name: string;
  /** 租户编码 */
  tenant_code: string;
  /** 客户端IP */
  client_ip: string;
  /** 登录设备 */
  device: string;
  /** 用户代理 */
  user_agent: string;
  /** 签发时间 */
  issued_at: string;
  /** 令牌有效期（秒） */
  expires_in: number;
}

/** Admin会话管理服务。 */
export interface BaseSessionService {
  /** 查询当前用户会话。 */
  GetCurrentBaseSession(request: GetCurrentBaseSessionRequest): Promise<BaseSession>;
  /** 撤销当前用户全部会话。 */
  RevokeAllBaseSessions(request: RevokeAllBaseSessionsRequest): Promise<Empty>;
}
