// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_redact_policy.proto

/* eslint-disable */
import type { Status } from "../../../common/v1/enum";
import type { Empty } from "../../../google/protobuf/empty";
import type { BaseRedactDirection } from "./base_redact_common";

/** 脱敏策略模式。 */
export enum BaseRedactPolicyMode {
  /** BASE_REDACT_POLICY_MODE_UNSPECIFIED - 未指定模式。 */
  BASE_REDACT_POLICY_MODE_UNSPECIFIED = 0,
  /** BASE_REDACT_POLICY_MODE_RULE - 使用规则模板处理。 */
  BASE_REDACT_POLICY_MODE_RULE = 1,
  /** BASE_REDACT_POLICY_MODE_HIDE - 替换为字段零值。 */
  BASE_REDACT_POLICY_MODE_HIDE = 2,
  /** BASE_REDACT_POLICY_MODE_FULL - 保留字段原值。 */
  BASE_REDACT_POLICY_MODE_FULL = 3,
}

/** 脱敏策略分页查询条件。 */
export interface PageBaseRedactPolicyRequest {
  /** Proto消息完整名称 */
  message_ref: string;
  /** 字段路径 */
  field_path: string;
  /** 场景编码 */
  scene_code: string;
  /** 接口操作 */
  operation: string;
  /** 脱敏方向 */
  direction?:
    | BaseRedactDirection
    | undefined;
  /** 策略模式 */
  mode?:
    | BaseRedactPolicyMode
    | undefined;
  /** 状态 */
  status?:
    | Status
    | undefined;
  /** 当前页码 */
  page_num: number;
  /** 每页数量 */
  page_size: number;
}

/** 脱敏策略分页响应。 */
export interface PageBaseRedactPolicyResponse {
  /** 脱敏策略列表 */
  base_redact_policies: BaseRedactPolicy[];
  /** 总数 */
  total: number;
}

/** 脱敏策略详情查询条件。 */
export interface GetBaseRedactPolicyRequest {
  id: number;
}

/** 脱敏策略表单。 */
export interface BaseRedactPolicyForm {
  /** 策略绑定ID */
  id: number;
  /** 字段目录ID */
  field_id: number;
  /** 规则模板ID */
  rule_id: number;
  /** 场景编码 */
  scene_code: string;
  /** 接口操作 */
  operation: string;
  /** 脱敏方向 */
  direction: BaseRedactDirection;
  /** 策略模式 */
  mode: BaseRedactPolicyMode;
  /** 优先级 */
  priority: number;
  /** 状态 */
  status: Status;
  /** 策略版本 */
  version: number;
  /** 备注 */
  remark: string;
}

/** 创建脱敏策略请求参数。 */
export interface CreateBaseRedactPolicyRequest {
  base_redact_policy: BaseRedactPolicyForm | undefined;
}

/** 更新脱敏策略请求参数。 */
export interface UpdateBaseRedactPolicyRequest {
  base_redact_policy: BaseRedactPolicyForm | undefined;
}

/** 删除脱敏策略请求参数。 */
export interface DeleteBaseRedactPolicyRequest {
  id: string;
}

/** 设置脱敏策略状态请求参数。 */
export interface SetBaseRedactPolicyStatusRequest {
  /** 策略绑定ID */
  id: number;
  /** 状态 */
  status: Status;
}

/** 脱敏策略。 */
export interface BaseRedactPolicy {
  /** 策略绑定ID */
  id: number;
  /** 字段目录ID */
  field_id: number;
  /** Proto消息完整名称 */
  message_ref: string;
  /** 字段路径 */
  field_path: string;
  /** Proto字段类型 */
  field_kind: string;
  /** 敏感字段类型 */
  sensitivity_type: string;
  /** 规则模板ID */
  rule_id: number;
  /** 规则编码 */
  rule_code: string;
  /** 规则名称 */
  rule_name: string;
  /** 规则类型 */
  rule_type: string;
  /** 规则参数 */
  rule: string;
  /** 场景编码 */
  scene_code: string;
  /** 接口操作 */
  operation: string;
  /** 脱敏方向 */
  direction: BaseRedactDirection;
  /** 策略模式 */
  mode: BaseRedactPolicyMode;
  /** 优先级 */
  priority: number;
  /** 状态 */
  status: Status;
  /** 策略版本 */
  version: number;
  /** 备注 */
  remark: string;
  /** 创建时间 */
  created_at: string;
  /** 更新时间 */
  updated_at: string;
}

/** Admin脱敏策略绑定服务。 */
export interface BaseRedactPolicyService {
  /** 查询脱敏策略分页列表。 */
  PageBaseRedactPolicy(request: PageBaseRedactPolicyRequest): Promise<PageBaseRedactPolicyResponse>;
  /** 查询脱敏策略详情。 */
  GetBaseRedactPolicy(request: GetBaseRedactPolicyRequest): Promise<BaseRedactPolicyForm>;
  /** 创建脱敏策略。 */
  CreateBaseRedactPolicy(request: CreateBaseRedactPolicyRequest): Promise<Empty>;
  /** 更新脱敏策略。 */
  UpdateBaseRedactPolicy(request: UpdateBaseRedactPolicyRequest): Promise<Empty>;
  /** 删除脱敏策略。 */
  DeleteBaseRedactPolicy(request: DeleteBaseRedactPolicyRequest): Promise<Empty>;
  /** 设置脱敏策略状态。 */
  SetBaseRedactPolicyStatus(request: SetBaseRedactPolicyStatusRequest): Promise<Empty>;
}
