// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               unknown
// source: system/admin/v1/base_rate_limit_rule.proto

/* eslint-disable */
import type { Status } from "../../../common/v1/enum";
import type { Empty } from "../../../google/protobuf/empty";

/** 限流规则选项查询条件。 */
export interface OptionBaseRateLimitRuleRequest {
  /** 规则关键字 */
  keyword: string;
}

/** 限流规则选项响应。 */
export interface OptionBaseRateLimitRuleResponse {
  /** 规则选项 */
  list: BaseRateLimitRuleOption[];
}

/** 限流规则选项。 */
export interface BaseRateLimitRuleOption {
  /** 规则ID */
  id: number;
  /** 规则名称 */
  label: string;
  /** 规则编码 */
  code: string;
  /** 限流算法类型 */
  rule_type: string;
  /** 默认规则参数 */
  default_params: string;
  /** 是否禁用 */
  disabled: boolean;
}

/** 限流规则分页查询条件。 */
export interface PageBaseRateLimitRuleRequest {
  /** 规则编码 */
  code: string;
  /** 规则名称 */
  name: string;
  /** 状态 */
  status?:
    | Status
    | undefined;
  /** 当前页码 */
  page_num: number;
  /** 每页数量 */
  page_size: number;
}

/** 限流规则分页响应。 */
export interface PageBaseRateLimitRuleResponse {
  /** 规则列表 */
  base_rate_limit_rules: BaseRateLimitRule[];
  /** 总数 */
  total: number;
}

/** 限流规则详情查询条件。 */
export interface GetBaseRateLimitRuleRequest {
  /** 规则ID */
  id: number;
}

/** 限流规则表单。 */
export interface BaseRateLimitRuleForm {
  /** 规则ID */
  id: number;
  /** 规则编码 */
  code: string;
  /** 规则名称 */
  name: string;
  /** 限流算法类型 */
  rule_type: string;
  /** 默认规则参数JSON */
  default_params: string;
  /** 状态 */
  status: Status;
  /** 备注 */
  remark: string;
}

/** 创建限流规则请求参数。 */
export interface CreateBaseRateLimitRuleRequest {
  /** 限流规则表单 */
  base_rate_limit_rule: BaseRateLimitRuleForm | undefined;
}

/** 更新限流规则请求参数。 */
export interface UpdateBaseRateLimitRuleRequest {
  /** 限流规则表单 */
  base_rate_limit_rule: BaseRateLimitRuleForm | undefined;
}

/** 删除限流规则请求参数。 */
export interface DeleteBaseRateLimitRuleRequest {
  /** 规则ID列表 */
  id: string;
}

/** 设置限流规则状态请求参数。 */
export interface SetBaseRateLimitRuleStatusRequest {
  /** 规则ID */
  id: number;
  /** 状态 */
  status: Status;
}

/** 限流规则模板。 */
export interface BaseRateLimitRule {
  /** 规则ID */
  id: number;
  /** 规则编码 */
  code: string;
  /** 规则名称 */
  name: string;
  /** 限流算法类型 */
  rule_type: string;
  /** 默认规则参数JSON */
  default_params: string;
  /** 状态 */
  status: Status;
  /** 备注 */
  remark: string;
  /** 创建时间 */
  created_at: string;
  /** 更新时间 */
  updated_at: string;
}

/** Admin限流规则模板服务。 */
export interface BaseRateLimitRuleService {
  /** 查询限流规则选项。 */
  OptionBaseRateLimitRule(request: OptionBaseRateLimitRuleRequest): Promise<OptionBaseRateLimitRuleResponse>;
  /** 查询限流规则分页列表。 */
  PageBaseRateLimitRule(request: PageBaseRateLimitRuleRequest): Promise<PageBaseRateLimitRuleResponse>;
  /** 查询限流规则详情。 */
  GetBaseRateLimitRule(request: GetBaseRateLimitRuleRequest): Promise<BaseRateLimitRuleForm>;
  /** 创建限流规则。 */
  CreateBaseRateLimitRule(request: CreateBaseRateLimitRuleRequest): Promise<Empty>;
  /** 更新限流规则。 */
  UpdateBaseRateLimitRule(request: UpdateBaseRateLimitRuleRequest): Promise<Empty>;
  /** 删除限流规则。 */
  DeleteBaseRateLimitRule(request: DeleteBaseRateLimitRuleRequest): Promise<Empty>;
  /** 设置限流规则状态。 */
  SetBaseRateLimitRuleStatus(request: SetBaseRateLimitRuleStatusRequest): Promise<Empty>;
}
