// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/project_document.proto

/* eslint-disable */

/** 项目文档树查询条件 */
export interface TreeProjectDocumentRequest {
}

/** 项目文档树响应 */
export interface TreeProjectDocumentResponse {
  /** 项目文档树 */
  projects: ProjectDocumentProject[];
}

/** 项目文档详情查询条件 */
export interface GetProjectDocumentRequest {
  /** 项目文档ID */
  id: string;
}

/** 项目文档目录项 */
export interface ProjectDocumentListItem {
  /** 项目文档ID */
  id: string;
  /** 项目内相对路径 */
  path: string;
  /** Markdown文件更新时间，RFC3339格式 */
  updated_at: string;
}

/** 项目文档树 */
export interface ProjectDocumentProject {
  /** 与OpenAPI文档一致的项目标识 */
  key: string;
  /** 与OpenAPI文档一致的项目名称 */
  name: string;
  /** 项目根目录下的文档 */
  documents: ProjectDocumentListItem[];
  /** 项目根目录下的子目录 */
  directories: ProjectDocumentDirectory[];
}

/** 项目文档目录节点 */
export interface ProjectDocumentDirectory {
  /** 目录名称 */
  name: string;
  /** 项目内相对目录路径 */
  path: string;
  /** 当前目录下的文档 */
  documents: ProjectDocumentListItem[];
  /** 当前目录下的子目录 */
  directories: ProjectDocumentDirectory[];
}

/** 项目文档 */
export interface ProjectDocument {
  /** 项目文档ID */
  id: string;
  /** 与OpenAPI文档一致的项目标识 */
  project_key: string;
  /** 与OpenAPI文档一致的项目名称 */
  project_name: string;
  /** 项目内相对路径 */
  path: string;
  /** Markdown文档内容 */
  content: string;
}

/** 项目文档服务 */
export interface ProjectDocumentService {
  /** 查询项目文档树 */
  TreeProjectDocument(request: TreeProjectDocumentRequest): Promise<TreeProjectDocumentResponse>;
  /** 查询项目文档详情 */
  GetProjectDocument(request: GetProjectDocumentRequest): Promise<ProjectDocument>;
}
