// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package module

import (
	"github.com/liujitcn/kratos-admin/backend/internal/biz/agent/model"
	biz2 "github.com/liujitcn/kratos-admin/backend/internal/biz/base"
	"github.com/liujitcn/kratos-admin/backend/internal/biz/base/ai"
	biz3 "github.com/liujitcn/kratos-admin/backend/internal/biz/system/admin"
	"github.com/liujitcn/kratos-admin/backend/internal/biz/system/admin/codegen"
	"github.com/liujitcn/kratos-admin/backend/internal/biz/system/admin/logstream"
	sse2 "github.com/liujitcn/kratos-admin/backend/internal/biz/system/admin/sse"
	biz4 "github.com/liujitcn/kratos-admin/backend/internal/biz/system/app"
	data2 "github.com/liujitcn/kratos-admin/backend/internal/data/gen/data"
	base2 "github.com/liujitcn/kratos-admin/backend/internal/server/base/v1"
	admin2 "github.com/liujitcn/kratos-admin/backend/internal/server/system/admin/v1"
	app2 "github.com/liujitcn/kratos-admin/backend/internal/server/system/app/v1"
	"github.com/liujitcn/kratos-admin/backend/internal/service/base/v1"
	"github.com/liujitcn/kratos-admin/backend/internal/service/system/admin/v1"
	"github.com/liujitcn/kratos-admin/backend/internal/service/system/app/v1"
	"github.com/liujitcn/kratos-admin/backend/internal/task"
	admin3 "github.com/liujitcn/kratos-admin/backend/internal/task/system/admin"
	"github.com/liujitcn/kratos-core/biz"
	"github.com/liujitcn/kratos-core/job"
	"github.com/liujitcn/kratos-core/module"
	"github.com/liujitcn/kratos-core/queue"
	"github.com/liujitcn/kratos-core/resource/docs"
	"github.com/liujitcn/kratos-core/resource/i18n"
	"github.com/liujitcn/kratos-core/resource/openapi"
	"github.com/liujitcn/kratos-core/sse"
	configv1 "github.com/liujitcn/kratos-kit/api/gen/go/config/v1"
	"github.com/liujitcn/kratos-kit/auth/authz/engine"
	"github.com/liujitcn/kratos-kit/auth/data"
	"github.com/liujitcn/kratos-kit/database/gorm"
)

// Injectors from wire.go:

// BuildModules 通过 Admin 内部 ProviderSet 装配协议服务。
func BuildModules(config *configv1.Bootstrap, databases map[string]*gorm.Client, baseCase *biz.BaseCase, authorizer engine.Engine, userToken *data.UserToken, jobRuntime *job.Job, sseRuntime *sse.SSE, docsRuntime *docs.Docs, catalog *i18n.I18n, openAPIRuntime *openapi.OpenAPI) (module.Modules, func(), error) {
	dataData, err := data2.NewData(databases)
	if err != nil {
		return nil, nil, err
	}
	transaction := data2.NewTransaction(dataData)
	aiSessionRepository := data2.NewAiSessionRepository(dataData)
	aiMessageRepository := data2.NewAiMessageRepository(dataData)
	aiSessionCase := biz2.NewAiSessionCase(baseCase, transaction, aiSessionRepository, aiMessageRepository)
	baseUserRepository := data2.NewBaseUserRepository(dataData)
	baseUserCase := biz2.NewBaseUserCase(baseCase, baseUserRepository)
	ai_Model, err := ParseAIModel(config)
	if err != nil {
		return nil, nil, err
	}
	responsesClient := model.NewResponsesClient(ai_Model)
	baseAPIRepository := data2.NewBaseAPIRepository(dataData)
	mcpCase, err := biz2.NewMcpCase(baseCase, baseAPIRepository)
	if err != nil {
		return nil, nil, err
	}
	baseDeptRepository := data2.NewBaseDeptRepository(dataData)
	basePostRepository := data2.NewBasePostRepository(dataData)
	baseRoleRepository := data2.NewBaseRoleRepository(dataData)
	baseTenantRepository := data2.NewBaseTenantRepository(dataData)
	casbinRuleRepository := data2.NewCasbinRuleRepository(dataData)
	baseMenuRepository := data2.NewBaseMenuRepository(dataData)
	baseAPII18NRepository := data2.NewBaseAPII18NRepository(dataData)
	baseAPICase := biz3.NewBaseAPICase(baseCase, openAPIRuntime, catalog, baseAPIRepository, baseAPII18NRepository)
	casbinRuleCase, err := biz3.NewCasbinRuleCase(casbinRuleRepository, baseMenuRepository, baseRoleRepository, baseTenantRepository, baseAPICase, authorizer)
	if err != nil {
		return nil, nil, err
	}
	baseRoleCase := biz3.NewBaseRoleCase(baseCase, transaction, baseRoleRepository, baseTenantRepository, casbinRuleCase)
	baseDeptCase := biz3.NewBaseDeptCase(baseCase, baseDeptRepository)
	baseI18NRepository := data2.NewBaseI18NRepository(dataData)
	baseLanguageRepository := data2.NewBaseLanguageRepository(dataData)
	baseLanguageCase := biz3.NewBaseLanguageCase(baseCase, transaction, baseLanguageRepository)
	baseTranslationCase := biz3.NewBaseTranslationCase(baseCase, transaction, baseI18NRepository, baseLanguageCase)
	baseMenuCase := biz3.NewBaseMenuCase(baseCase, transaction, baseMenuRepository, baseRoleRepository, casbinRuleCase, baseTranslationCase)
	bizBaseRoleCase := biz2.NewBaseRoleCase(baseCase, baseRoleRepository, baseTenantRepository)
	bizBaseUserCase := biz3.NewBaseUserCase(baseCase, transaction, baseUserRepository, baseDeptRepository, basePostRepository, baseRoleCase, baseDeptCase, baseMenuCase, bizBaseRoleCase)
	baseTenantCase := biz3.NewBaseTenantCase(baseCase, transaction, baseTenantRepository, baseDeptRepository, baseRoleRepository, baseUserRepository, casbinRuleRepository, casbinRuleCase)
	fileCase := biz2.NewFileCase(baseCase)
	authCase := biz3.NewAuthCase(baseCase, bizBaseUserCase, baseRoleCase, baseDeptCase, baseTenantCase, baseMenuCase, fileCase)
	authService := admin.NewAuthService(authCase)
	baseApiService := admin.NewBaseApiService(baseAPICase)
	baseAreaRepository := data2.NewBaseAreaRepository(dataData)
	baseAreaCase := biz3.NewBaseAreaCase(baseCase, baseAreaRepository)
	baseAreaService := admin.NewBaseAreaService(baseAreaCase)
	baseConfigRepository := data2.NewBaseConfigRepository(dataData)
	baseConfigCase := biz3.NewBaseConfigCase(baseCase, transaction, baseConfigRepository, baseTranslationCase)
	baseConfigService := admin.NewBaseConfigService(baseConfigCase)
	baseDeptService := admin.NewBaseDeptService(baseDeptCase)
	baseDictRepository := data2.NewBaseDictRepository(dataData)
	baseDictItemRepository := data2.NewBaseDictItemRepository(dataData)
	baseDictItemCase := biz3.NewBaseDictItemCase(baseCase, transaction, baseDictRepository, baseDictItemRepository, baseTranslationCase)
	baseDictCase := biz3.NewBaseDictCase(baseCase, transaction, baseDictRepository, baseDictItemCase, baseTranslationCase)
	baseDictService := admin.NewBaseDictService(baseDictCase, baseDictItemCase)
	baseJobRepository := data2.NewBaseJobRepository(dataData)
	baseJobLogRepository := data2.NewBaseJobLogRepository(dataData)
	baseJobLogCase := biz3.NewBaseJobLogCase(baseCase, baseJobLogRepository)
	baseJobCase := biz3.NewBaseJobCase(baseCase, jobRuntime, baseJobRepository, baseJobLogCase)
	baseJobService := admin.NewBaseJobService(baseJobCase, baseJobLogCase)
	baseLanguageService := admin.NewBaseLanguageService(baseLanguageCase)
	baseLogRepository := data2.NewBaseLogRepository(dataData)
	baseLogCase := biz3.NewBaseLogCase(baseCase, baseLogRepository)
	baseLogService := admin.NewBaseLogService(baseLogCase)
	baseMenuService := admin.NewBaseMenuService(baseMenuCase)
	basePostCase := biz3.NewBasePostCase(baseCase, transaction, basePostRepository, baseUserRepository)
	basePostService := admin.NewBasePostService(basePostCase)
	baseRoleService := admin.NewBaseRoleService(baseRoleCase)
	baseTenantService := admin.NewBaseTenantService(baseTenantCase)
	baseThirdAccountRepository := data2.NewBaseThirdAccountRepository(dataData)
	baseThirdAccountCase := biz2.NewBaseThirdAccountCase(baseCase, baseThirdAccountRepository)
	baseThirdAccountService := admin.NewBaseThirdAccountService(baseThirdAccountCase)
	baseI18nService := admin.NewBaseI18nService(baseTranslationCase)
	baseUserService := admin.NewBaseUserService(bizBaseUserCase)
	codeGenTableRepository := data2.NewCodeGenTableRepository(dataData)
	codeGenColumnRepository := data2.NewCodeGenColumnRepository(dataData)
	codeGenColumnCase := biz3.NewCodeGenColumnCase(baseCase, codeGenColumnRepository, transaction, baseDictRepository, codeGenTableRepository)
	codeGenProtoRepository := data2.NewCodeGenProtoRepository(dataData)
	codeGenProtoCase := biz3.NewCodeGenProtoCase(baseCase, codeGenProtoRepository, transaction, baseAPIRepository, codeGenTableRepository, codeGenColumnCase)
	codeGenTableCase := biz3.NewCodeGenTableCase(baseCase, codeGenTableRepository, transaction, baseDictRepository, baseDictItemRepository, baseMenuCase, codeGenColumnCase, codeGenProtoCase)
	baseMigrationRepository := data2.NewBaseMigrationRepository(dataData)
	baseMigrationCase := biz3.NewBaseMigrationCase(baseCase, baseMigrationRepository)
	manager := codegen.NewManager()
	codeGenCase := biz3.NewCodeGenCase(baseCase, transaction, baseAPICase, codeGenTableCase, codeGenColumnCase, codeGenProtoCase, baseMenuCase, baseMigrationCase, baseLanguageCase, manager)
	codeGenService := admin.NewCodeGenService(codeGenCase)
	codeGenColumnService := admin.NewCodeGenColumnService(codeGenColumnCase)
	codeGenProtoService := admin.NewCodeGenProtoService(codeGenProtoCase)
	codeGenTableService := admin.NewCodeGenTableService(codeGenTableCase)
	baseMigrationService := admin.NewBaseMigrationService(baseMigrationCase)
	opsMonitoringCase := biz3.NewOpsMonitoringCase(baseCase, baseLogRepository)
	opsMonitoringService := admin.NewOpsMonitoringService(opsMonitoringCase)
	hub := logstream.DefaultHub()
	runtimeLogCase, err := biz3.NewRuntimeLogCase(baseCase, hub, sseRuntime)
	if err != nil {
		return nil, nil, err
	}
	runtimeLogService := admin.NewRuntimeLogService(runtimeLogCase)
	projectDocumentService := admin.NewProjectDocumentService(docsRuntime, catalog)
	services := admin2.Services{
		Auth:             authService,
		BaseAPI:          baseApiService,
		BaseArea:         baseAreaService,
		BaseConfig:       baseConfigService,
		BaseDept:         baseDeptService,
		BaseDict:         baseDictService,
		BaseJob:          baseJobService,
		BaseLanguage:     baseLanguageService,
		BaseLog:          baseLogService,
		BaseMenu:         baseMenuService,
		BasePost:         basePostService,
		BaseRole:         baseRoleService,
		BaseTenant:       baseTenantService,
		BaseThirdAccount: baseThirdAccountService,
		BaseI18n:         baseI18nService,
		BaseUser:         baseUserService,
		CodeGen:          codeGenService,
		CodeGenColumn:    codeGenColumnService,
		CodeGenProto:     codeGenProtoService,
		CodeGenTable:     codeGenTableService,
		BaseMigration:    baseMigrationService,
		OpsMonitoring:    opsMonitoringService,
		RuntimeLog:       runtimeLogService,
		ProjectDocument:  projectDocumentService,
	}
	adminTools, err := ParseAdminAgentTools(services)
	if err != nil {
		return nil, nil, err
	}
	baseUserCase2 := biz4.NewBaseUserCase(baseCase, baseUserRepository)
	oauthManager, err := ParseOAuthManager(config)
	if err != nil {
		return nil, nil, err
	}
	bizAuthCase := biz4.NewAuthCase(baseCase, baseUserCase2, oauthManager)
	appAuthService := app.NewAuthService(bizAuthCase)
	bizBaseAreaCase := biz4.NewBaseAreaCase(baseCase, baseAreaRepository)
	appBaseAreaService := app.NewBaseAreaService(bizBaseAreaCase)
	bizBaseDictItemCase := biz4.NewBaseDictItemCase(baseCase, baseDictRepository, baseDictItemRepository)
	bizBaseDictCase := biz4.NewBaseDictCase(baseCase, baseDictRepository, bizBaseDictItemCase, baseTranslationCase)
	appBaseDictService := app.NewBaseDictService(bizBaseDictCase)
	bizBaseMenuCase := biz4.NewBaseMenuCase(baseCase, baseMenuRepository, baseTranslationCase)
	appBaseMenuService := app.NewBaseMenuService(bizBaseMenuCase)
	appServices := app2.Services{
		Auth:     appAuthService,
		BaseArea: appBaseAreaService,
		BaseDict: appBaseDictService,
		BaseMenu: appBaseMenuService,
	}
	appTools, err := ParseAppAgentTools(appServices)
	if err != nil {
		return nil, nil, err
	}
	runtime := ai.NewRuntime(responsesClient, mcpCase, adminTools, appTools)
	aiMessageCase := biz2.NewAiMessageCase(baseCase, transaction, aiMessageRepository, aiSessionCase, baseUserCase, runtime)
	aiSessionService := base.NewAiSessionService(aiSessionCase, aiMessageCase)
	aiToolCase := biz2.NewAiToolCase(baseCase, runtime)
	aiToolService := base.NewAiToolService(aiToolCase)
	aiMessageService := base.NewAiMessageService(aiMessageCase)
	configCase := biz2.NewConfigCase(baseCase, baseConfigRepository, baseI18NRepository, baseLanguageRepository)
	configService := base.NewConfigService(configCase)
	languageCase := biz2.NewLanguageCase(baseCase, baseLanguageRepository)
	languageService := base.NewLanguageService(languageCase)
	fileService := base.NewFileService(fileCase)
	bizBaseDeptCase := biz2.NewBaseDeptCase(baseCase, baseDeptRepository)
	loginCase := biz2.NewLoginCase(baseCase, bizBaseDeptCase, bizBaseRoleCase, baseUserCase, baseTenantRepository, baseDictRepository, baseDictItemRepository, userToken)
	loginService := base.NewLoginService(loginCase)
	oauthCase := biz2.NewOauthCase(baseCase, transaction, baseThirdAccountCase, baseUserCase, bizBaseRoleCase, bizBaseDeptCase, loginCase, configCase, oauthManager)
	oauthService := base.NewOauthService(oauthCase)
	mcpService := base.NewMcpService(mcpCase)
	sseCase := biz2.NewSseCase(baseCase, sseRuntime)
	sseService := base.NewSseService(sseCase)
	baseServices := &base2.Services{
		AiSession: aiSessionService,
		AiTool:    aiToolService,
		AiMessage: aiMessageService,
		Config:    configService,
		Language:  languageService,
		File:      fileService,
		Login:     loginService,
		Oauth:     oauthService,
		Mcp:       mcpService,
		Sse:       sseService,
	}
	adminServices := &admin2.Services{
		Auth:             authService,
		BaseAPI:          baseApiService,
		BaseArea:         baseAreaService,
		BaseConfig:       baseConfigService,
		BaseDept:         baseDeptService,
		BaseDict:         baseDictService,
		BaseJob:          baseJobService,
		BaseLanguage:     baseLanguageService,
		BaseLog:          baseLogService,
		BaseMenu:         baseMenuService,
		BasePost:         basePostService,
		BaseRole:         baseRoleService,
		BaseTenant:       baseTenantService,
		BaseThirdAccount: baseThirdAccountService,
		BaseI18n:         baseI18nService,
		BaseUser:         baseUserService,
		CodeGen:          codeGenService,
		CodeGenColumn:    codeGenColumnService,
		CodeGenProto:     codeGenProtoService,
		CodeGenTable:     codeGenTableService,
		BaseMigration:    baseMigrationService,
		OpsMonitoring:    opsMonitoringService,
		RuntimeLog:       runtimeLogService,
		ProjectDocument:  projectDocumentService,
	}
	services2 := &app2.Services{
		Auth:     appAuthService,
		BaseArea: appBaseAreaService,
		BaseDict: appBaseDictService,
		BaseMenu: appBaseMenuService,
	}
	modules := NewModules(baseServices, adminServices, services2)
	return modules, func() {
	}, nil
}

// BuildTasks 通过最小依赖集合装配 Admin 定时任务。
func BuildTasks(databases map[string]*gorm.Client, baseCase *biz.BaseCase) (job.Tasks, func(), error) {
	dataData, err := data2.NewData(databases)
	if err != nil {
		return nil, nil, err
	}
	transaction := data2.NewTransaction(dataData)
	baseI18NRepository := data2.NewBaseI18NRepository(dataData)
	baseLanguageRepository := data2.NewBaseLanguageRepository(dataData)
	baseLanguageCase := biz3.NewBaseLanguageCase(baseCase, transaction, baseLanguageRepository)
	baseTranslationCase := biz3.NewBaseTranslationCase(baseCase, transaction, baseI18NRepository, baseLanguageCase)
	baseMenuRepository := data2.NewBaseMenuRepository(dataData)
	baseDictRepository := data2.NewBaseDictRepository(dataData)
	baseDictItemRepository := data2.NewBaseDictItemRepository(dataData)
	baseConfigRepository := data2.NewBaseConfigRepository(dataData)
	baseTranslationTask := admin3.NewBaseTranslationTask(baseTranslationCase, baseMenuRepository, baseDictRepository, baseDictItemRepository, baseConfigRepository)
	tasks := task.NewTask(baseTranslationTask)
	return tasks, func() {
	}, nil
}

// BuildStreams 通过最小依赖集合装配 Admin SSE 流。
func BuildStreams(databases map[string]*gorm.Client, baseCase *biz.BaseCase) (sse.Streams, func(), error) {
	manager := codegen.NewManager()
	sseCodegen := sse2.NewCodegen(manager)
	dataData, err := data2.NewData(databases)
	if err != nil {
		return nil, nil, err
	}
	baseLogRepository := data2.NewBaseLogRepository(dataData)
	opsMonitoringCase := biz3.NewOpsMonitoringCase(baseCase, baseLogRepository)
	opsMonitoring := sse2.NewOpsMonitoring(opsMonitoringCase)
	hub := logstream.DefaultHub()
	runtimeConsole := sse2.NewRuntimeConsole(hub)
	streams, cleanup := sse2.NewStreams(sseCodegen, opsMonitoring, runtimeConsole)
	return streams, func() {
		cleanup()
	}, nil
}

// BuildQueueConsumers 装配 Admin 队列消费者集合。
func BuildQueueConsumers() queue.Consumers {
	consumers := NewQueueConsumers()
	return consumers
}
