// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: base/v1/enum.proto

/* eslint-disable */

/** AI 助手消息状态 */
export enum AiMessageStatus {
  /** UNKNOWN_AMS - 未知AI助手消息状态 */
  UNKNOWN_AMS = 0,
  /** GENERATING_AMS - 生成中 */
  GENERATING_AMS = 1,
  /** SUCCESS_AMS - 成功 */
  SUCCESS_AMS = 2,
  /** FAILED_AMS - 失败 */
  FAILED_AMS = 3
}

/** 终端类型 */
export enum Terminal {
  /** UNKNOWN_TERMINAL - 未知终端 */
  UNKNOWN_TERMINAL = 0,
  /** TERMINAL_APP - 移动端 */
  TERMINAL_APP = 1,
  /** TERMINAL_ADMIN - 管理端 */
  TERMINAL_ADMIN = 2
}

/** 系统配置位置 */
export enum BaseConfigSite {
  UNKNOWN_BCS = 0,
  /** SYSTEM - 系统内使用 */
  SYSTEM = 1,
  /** ADMIN - 管理端 */
  ADMIN = 2,
  /** APP - 移动端 */
  APP = 3
}

/** 密码加密场景枚举 */
export enum PasswordCryptoScene {
  /** UNKNOWN_PCS - 未指定密码加密场景 */
  UNKNOWN_PCS = 0,
  /** LOGIN - 登录密码加密场景 */
  LOGIN = 1,
  /** CREATE_BASE_USER - 新增后台用户密码加密场景 */
  CREATE_BASE_USER = 2,
  /** RESET_BASE_USER_PASSWORD - 重置后台用户密码加密场景 */
  RESET_BASE_USER_PASSWORD = 3,
  /** UPDATE_USER_PASSWORD - 个人修改密码加密场景 */
  UPDATE_USER_PASSWORD = 4
}
