// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               unknown
// source: base/v1/secret_crypto.proto

/* eslint-disable */

/** 敏感字段临时公钥获取条件 */
export interface GetSecretPublicKeyRequest {
}

/** 敏感字段临时公钥响应 */
export interface GetSecretPublicKeyResponse {
  /** 临时密钥ID */
  key_id: string;
  /** 临时公钥 */
  public_key: string;
  /** 加密算法 */
  algorithm: string;
  /** 随机值 */
  nonce: string;
  /** 有效时间，单位秒 */
  expires_in: number;
}

/** 密钥字段查看条件 */
export interface RevealSecretFieldRequest {
  /** 资源标识，如 ai_provider、base_oauth_provider、base_message_provider */
  resource: string;
  /** 记录ID */
  id: number;
  /** 字段名，如 api_key、client_secret */
  field: string;
}

/** 密钥字段查看响应 */
export interface RevealSecretFieldResponse {
  /** 密钥明文 */
  text: string;
}

/** 敏感字段加密公共服务 */
export interface SecretCryptoService {
  /** 获取敏感字段临时公钥，同一次提交的多个密文字段共用该公钥 */
  GetSecretPublicKey(request: GetSecretPublicKeyRequest): Promise<GetSecretPublicKeyResponse>;
  /** 查看密钥字段明文，仅允许查询注册过的密钥字段 */
  RevealSecretField(request: RevealSecretFieldRequest): Promise<RevealSecretFieldResponse>;
}
