// Code generated by project-docs. DO NOT EDIT.

// Package projectdocs 保存 project-docs 生成的嵌入目录。
package projectdocs

import _ "embed"

// CatalogData 是构建期生成的项目文档目录。
//
//go:embed "assets/catalog.json"
var CatalogData []byte
