// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: common/v1/enum.proto

/* eslint-disable */

/** 状态 */
export enum Status {
  /** UNKNOWN - 未知状态 */
  UNKNOWN = 0,
  /** ENABLE - 启用 */
  ENABLE = 1,
  /** DISABLE - 禁用 */
  DISABLE = 2
}
