syntax = "proto3";

package base.v1;

import "gnostic/openapi/v3/annotations.proto";
import "google/api/annotations.proto";

// 语言公共服务。
service LanguageService {
  // 查询当前支持的语言选项。
  rpc OptionLanguage(OptionLanguageRequest) returns (OptionLanguageResponse) {
    option (google.api.http) = {
      get: "/api/v1/base/language"
    };
  }
}

// 查询语言选项请求参数。
message OptionLanguageRequest {}

// 语言选择项。
message LanguageItem {
  string language_code = 1 [(gnostic.openapi.v3.property) = {description: "标准语言代码"}]; // 标准语言代码

  string native_name = 2 [(gnostic.openapi.v3.property) = {description: "本地语言名称"}]; // 本地语言名称
}

// 当前支持的语言选项查询结果。
message OptionLanguageResponse {
  repeated LanguageItem languages = 1 [(gnostic.openapi.v3.property) = {description: "当前支持的语言列表"}]; // 当前支持的语言列表
}
