ai:
    model:
        cloud:
            api_key: ENC[RVnCafkm9lOJ4wO3aD6ieQOo8uB14bP3Uelbt9UzPF8WZzSfT5ISdYPLstaGuOUKO0Pu7sq86aUOuQZBEPJh_-4JJOXiK5jUscUofhB4jSuIHAnsS2rlWfkW2sn9v34]
            base_url: http://subapi.openclawrouter.site/v1
        max_retries: 2
        max_tokens: 1024
        model_name: gpt-5.6
        temperature: 0.2
        timeout_seconds: 60
        type: CLOUD_MODEL
