data:
  database:
    debug: true
    driver: mysql
    enable_migrate: true
    source: root:112233@tcp(192.168.60.52:3306)/kratos_admin?charset=utf8mb4&parseTime=True&loc=Local&timeout=1000ms
  redis:
    addr:
      - 192.168.60.52:6379
    db: 0
    password: '112233'
  queue: {}
