registry:
    type: consul
    consul:
        address: 127.0.0.1:8500
        health_check: false
        scheme: http
        token: ENC[EFWFihapTf4nRtz3DFYliocgUIl9vdGrUGsThiKPbhCwaDmSCg-2GYjA9PeH-RnpP6KhYDqVFgEd5p4ANWTfiA]
