registry:
  type: "etcd"

  consul:
    address: "localhost:8500"
    scheme: "http"
    heartbeat: false
    health_check: false
    health_check_interval: 5

  etcd:
    endpoints:
      - 127.0.0.1:2379
    username: root
    password: "112233"

  zookeeper:
    endpoints:
      - "localhost:8500"
    timeout: 10s
